BEGIN TRANSACTION

DELETE sal.fat_factores_tipo_planilla WHERE EXISTS (SELECT NULL FROM sal.tpl_tipo_planilla WHERE tpl_codigo = fat_codtpl AND tpl_codigo_visual IN ('4'))
DELETE sal.ftp_formulacion_tipos_planilla WHERE EXISTS (SELECT NULL FROM sal.tpl_tipo_planilla WHERE tpl_codigo = ftp_codtpl AND tpl_codigo_visual IN ('4'))

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = 'f2c43129-55ca-4e41-8ba0-76cdcd196ac0';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('f2c43129-55ca-4e41-8ba0-76cdcd196ac0','FiltroEmpleadosSemanal','Determina que empleado participa en la planilla','Function FiltroEmpleadosSemanal

FiltroEmpleadosSemanal = (Empleados.Fields("emp_fecha_ingreso").Value <= Periodos.Fields("ppl_fecha_fin").Value) And Empleados.Fields("emp_codtpl").Value = Periodos.Fields("ppl_codtpl").Value

End Function','boolean','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = '5452fadc-329b-4ec4-8222-ae3e1555941e';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('5452fadc-329b-4ec4-8222-ae3e1555941e','SalarioPorHoraSemanal','Salario por Hora del Empleado','Function SalarioPorHoraSemanal()

valor = 0.00

'' Calcula Salario Actual
If Not (RubrosSalario.Bof And RubrosSalario.Eof) Then
	If IsNull(RubrosSalario.Fields("ese_valor").Value ) Then
		valor = 0.00
	Else
		If RubrosSalario.Fields("ese_exp_valor").Value = "Diario" Then
			valor = RubrosSalario.Fields("ese_valor").Value / ParametrosAplicacion.Fields("horas_por_dia").Value
		ElseIf RubrosSalario.Fields("ese_exp_valor").Value = "Mensual" Then
			valor = RubrosSalario.Fields("ese_valor").Value / ParametrosAplicacion.Fields("horas_por_mes").Value
		Else
			valor = RubrosSalario.Fields("ese_valor").Value
		End If
	End If
End If
   
SalarioPorHoraSemanal = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = '4f10b2c1-eee5-4a98-b336-2a16db7c4bdd';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('4f10b2c1-eee5-4a98-b336-2a16db7c4bdd','ExtraordinarioSemanal','Determina el Monto devengado el empleado por Horas Extras Mensual','Function ExtraordinarioSemanal()

valor = 0.00
total = 0.00
horas = 0

If HorasExtras.RecordCount > 0 Then
  
  HorasExtras.MoveFirst

  Do Until HorasExtras.Eof

	valor = Round(HorasExtras.Fields("ext_valor_a_pagar").Value, 2)
	
	horas = Round(HorasExtras.Fields("ext_num_horas").Value, 2)
	
	total = total + valor
	
	HorasExtras.Fields("ext_aplicado_planilla").Value = 1
	
	If Not IsNull(HorasExtras.Fields("the_codtig").Value) And valor > 0.00 Then
   		agrega_ingresos_historial Agrupadores, _
								IngresosEstaPlanilla, _
								Empleados.Fields("emp_codigo").Value, _
								Periodos.Fields("ppl_codigo").Value, _
								HorasExtras.Fields("the_codtig").Value, _
								Round(valor, 2), _
								Periodos.Fields("tpl_codmon").Value, _
								Round(horas, 2), "Horas"		
	End If
	
	HorasExtras.MoveNext
  Loop

End If

ExtraordinarioSemanal = total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = 'b529a4c9-9d70-49d3-a55b-3f019926fa23';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('b529a4c9-9d70-49d3-a55b-3f019926fa23','TiempoNoTrabajadoSemanal','Valor por tiempo no trabajado con goce de sueldo','Function TiempoNoTrabajadoSemanal()

dias = 0.00
horas = 0.00
valor = 0.00
sal = 0.00

sal = Factores("SalarioPorHoraSemanal").Value

If TiemposNoTrabajados.RecordCount > 0 Then         
	
	TiemposNoTrabajados.MoveFirst         
	
	Do While Not TiemposNoTrabajados.Eof              

		dias = dias + CDbl(TiemposNoTrabajados.Fields("dias").Value)

		TiemposNoTrabajados.MoveNext  
		
	Loop         

End If    

horas = dias * ParametrosAplicacion.Fields("horas_por_dia").Value
valor = sal * horas

If Not IsNull(Factores("TiempoNoTrabajadoSemanal").CodTipoIngreso) And valor > 0.00 Then    
	agrega_ingresos_historial Agrupadores, _
								IngresosEstaPlanilla, _
								Empleados.Fields("emp_codigo").Value, _
								Periodos.Fields("ppl_codigo").Value, _
								Factores("TiempoNoTrabajadoSemanal").CodTipoIngreso, _
								valor, RubrosSalario.Fields("ese_codmon").Value, horas, "Horas"
End If

TiempoNoTrabajadoSemanal = valor  

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = '0777d6c9-32bc-480e-abd2-a4b063cfb3c7';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('0777d6c9-32bc-480e-abd2-a4b063cfb3c7','PrestacionEmpleadoSemanal','Prestaciones del Empleado Mensual','Function PrestacionEmpleadoSemanal()

valor = 0.00
total = 0.00

If PrestacionesEmpleado.RecordCount > 0 Then
	PrestacionesEmpleado.MoveFirst
	Do Until PrestacionesEmpleado.Eof

		valor = Round(PrestacionesEmpleado.Fields("ppp_valor").Value, 2)

		If Not IsNull(PrestacionesEmpleado.Fields("pre_codtig").Value) And valor > 0.00 Then
			agrega_ingresos_historial Agrupadores, _ 
						IngresosEstaPlanilla, _
						Empleados.Fields("emp_codigo").Value, _
						Periodos.Fields("ppl_codigo").Value, _
						PrestacionesEmpleado.Fields("pre_codtig").Value , _
						valor, _
						PrestacionesEmpleado.Fields("ppp_codmon").Value, 0.00, "Horas"

			total = total + valor
		End If

		PrestacionesEmpleado.MoveNext
	Loop
End If

PrestacionEmpleadoSemanal = total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = '2672e41e-a714-46d6-b3a9-fa55d384d652';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('2672e41e-a714-46d6-b3a9-fa55d384d652','VacacionesSemanal','Determina el monto a pagar al empleado por los días que está de vacaciones durante la planilla Mensual','Function VacacionesSemanal()

valor = 0.00
horas = 0.00

If Vacaciones.RecordCount > 0 Then
	
	Vacaciones.MoveFirst

	If Not (Vacaciones.Bof And Vacaciones.Eof) Then 
	
		Do While Not Vacaciones.Eof   
		
			valor = valor + Vacaciones.Fields("vca_valor").Value
			horas = horas + Vacaciones.Fields("vca_tiempo").Value
		
		Vacaciones.MoveNext
		
		Loop
	End If
End If

If Not IsNull(Factores("VacacionesSemanal").CodTipoIngreso) And valor > 0.00 Then
      agrega_ingresos_historial Agrupadores, _
                                IngresosEstaPlanilla, _
                                Empleados.Fields("emp_codigo").Value, _
                                Periodos.Fields("ppl_codigo").Value, _
                                Factores("VacacionesSemanal").CodTipoIngreso, _
                                valor, RubrosSalario.Fields("ese_codmon").Value, horas, "Horas"

End If

VacacionesSemanal = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = '93e3833e-4acb-4e30-9952-dc14b82b001c';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('93e3833e-4acb-4e30-9952-dc14b82b001c','PrestacionIncapacidadSemanal','Complemento por suspension del seguro social Mensual','Function PrestacionIncapacidadSemanal()

valor = 0.00
dias = 0.00
total = 0.00
horas = 0.00

If Incapacidades.RecordCount > 0 Then
 
  Incapacidades.MoveFirst

  	If Not (Incapacidades.Bof And Incapacidades.Eof) Then 

		Do While Not Incapacidades.Eof   
		
			dias = CDbl(Incapacidades.Fields("pie_dias").Value)
			valor = CDbl(Incapacidades.Fields("pie_valor_a_pagar").Value)
			horas = dias * ParametrosAplicacion.Fields("horas_por_dia").Value
			
			total = total + valor
			
			If Not IsNull(Incapacidades.Fields("txi_codtig").Value) And valor > 0.00 Then
				agrega_ingresos_historial Agrupadores, _
				                    IngresosEstaPlanilla, _
				                    Empleados.Fields("emp_codigo").Value, _
				                    Periodos.Fields("ppl_codigo").Value, _
				                    Incapacidades.Fields("txi_codtig").Value, _
				                    valor, RubrosSalario.Fields("ese_codmon").Value, horas, "Horas"
			End If
			
			
			Incapacidades.MoveNext
		
		Loop

 	End If
	

End If

PrestacionIncapacidadSemanal = total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = '50107445-fb44-467f-b4fc-d7e7c2ad9431';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('50107445-fb44-467f-b4fc-d7e7c2ad9431','IngresoCiclicoSemanal','Pagos Fijos realizados al empleado mensualmente Mensual','Function IngresoCiclicoSemanal()

valor = 0.00

''''debemos garantizarnos que el cursor tiene por lo menos un registro para este empleado
If Not (IngresosCiclicos.Bof And IngresosCiclicos.Eof)Then
	IngresosCiclicos.MoveFirst
	
	Do Until IngresosCiclicos.Eof
		
		valor = valor + IngresosCiclicos.Fields("cic_valor_cuota").Value
		
		IngresosCiclicos.Fields("cic_aplicado_planilla").Value = 1
		
		If valor > 0 Then
			agrega_ingresos_historial Agrupadores, _
										IngresosEstaPlanilla, _
										Empleados.Fields("emp_codigo").Value, _
										Periodos.Fields("ppl_codigo").Value, _
										IngresosCiclicos.Fields("igc_codtig").Value, _
										Round(IngresosCiclicos.Fields("cic_valor_cuota").Value, 0), _
										IngresosCiclicos.Fields("igc_codmon").Value, 0.00, "Horas"
		End If

		IngresosCiclicos.MoveNext
	Loop

End If

IngresoCiclicoSemanal = Round(valor, 0)
	
End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = '734664ab-96db-40ed-84ce-2e8d01ce1681';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('734664ab-96db-40ed-84ce-2e8d01ce1681','IngresoEventualSemanal','Pago de Ingresos Eventuales Mensual','Function IngresoEventualSemanal()

total = 0.00
valor = 0.00
horas = 0.00

If IngresosEventuales.RecordCount > 0 Then
	IngresosEventuales.MoveFirst
	
	Do Until IngresosEventuales.Eof
	
		valor = Round(IngresosEventuales.Fields("oin_valor_a_pagar").Value, 2)
		
		horas = Round(valor / Factores("SalarioPorHoraSemanal").Value, 2)
		
		IngresosEventuales.Fields("oin_aplicado_planilla").Value = 1
		
		agrega_ingresos_historial Agrupadores, _
									IngresosEstaPlanilla, _
									Empleados.Fields("emp_codigo").Value, _
									Periodos.Fields("ppl_codigo").Value, _
									IngresosEventuales.Fields("oin_codtig").Value, _
									valor, IngresosEventuales.Fields("oin_codmon").Value, horas, "Horas"
									
		total = total + valor
		
		IngresosEventuales.MoveNext
	Loop
End If

IngresoEventualSemanal = total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = 'db75622a-f2d4-4254-acfb-b6c8cca3cff9';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('db75622a-f2d4-4254-acfb-b6c8cca3cff9','TotalIngresosSemanal','Suma de Todos los Ingresos Devengados por el Empleado en el periodo Mensual','Function TotalIngresosSemanal()

valor = 0.00

valor = Round(Factores("ExtraordinarioSemanal").Value + _
	Factores("PrestacionEmpleadoSemanal").Value + _
	Factores("VacacionesSemanal").Value + _
	Factores("PrestacionIncapacidadSemanal").Value + _
	Factores("IngresoCiclicoSemanal").Value + _
	Factores("IngresoEventualSemanal").Value, 2)    

TotalIngresosSemanal = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = '076530dc-4f80-4881-aa81-2dc10a11534d';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('076530dc-4f80-4881-aa81-2dc10a11534d','SeguroSocialSemanal','Determina el Monto a Descontar por concepto de CCSS al empleado en el periodo Mensual','Function SeguroSocialSemanal()

afecto = 0.00
cuota = 0.00
patronal = 0.00
por_cuota = 0.00
pat_cuota = 0.00			 
codtdc = 0
liquido = Factores("TotalIngresosSemanal").Value

If Empleados.Fields("aplica_seguro_social").Value Then
	
	If Empleados.Fields("emp_es_jubilado").Value Then
		por_cuota = ParametrosAplicacion.Fields("porc_jubilado_seguro_social").Value
		codtdc = ParametrosAplicacion.Fields("codtdc_ccss_jubilado").Value
	Else
		por_cuota = ParametrosAplicacion.Fields("porc_empleado_seguro_social").Value
		codtdc = ParametrosAplicacion.Fields("codtdc_ccss").Value
	End If
		
	pat_cuota = ParametrosAplicacion.Fields("porc_patrono_seguro_social").Value

	afecto = Agrupadores("CRBaseCalculoCCSS").Value
  
	cuota = por_cuota / 100.00 * afecto
	
	If cuota < 0.00 Then 
		cuota = 0.00       
	End If
	
	patronal = Round(pat_cuota / 100.00 * afecto,2)
	
	If patronal < 0.00 Then  
		patronal = 0.00  
	End If                                   
	
	'' inserta el registro en la tabla de descuentos  
	If codtdc > 0 And cuota > 0.00 And liquido - cuota >= 0.00 Then       
	 agrega_descuentos_historial Agrupadores, _
								DescuentosEstaPlanilla, _
								Empleados.Fields("emp_codigo").Value, _
								Periodos.Fields("ppl_codigo").Value, _
								codtdc, _
								Round(cuota, 2), Round(patronal,2), afecto, Periodos.Fields("tpl_codmon").Value, _
								0.00, "Horas"
	End If
End If

SeguroSocialSemanal = Round(cuota, 2)

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = '504d1f26-ec7c-483d-a729-7a373bce8d0d';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('504d1f26-ec7c-483d-a729-7a373bce8d0d','BancoPopularSemanal','Valor del descuento de banco popular','Function BancoPopularSemanal()

afecto = 0.00
cuota = 0.00
por_cuota = 0.00
liquido = Factores("TotalIngresosSemanal").Value - _
	Factores("SeguroSocialSemanal").Value

If Empleados.Fields("aplica_banco_popular").Value Then
	
	por_cuota = ParametrosAplicacion.Fields("banco_popular_porcentaje").Value

	afecto = Agrupadores("CRBaseCalculoBP").Value
  
	cuota = por_cuota / 100.00 * afecto
	
	If cuota < 0.00 Then 
		cuota = 0.00       
	End If
	
	'' inserta el registro en la tabla de descuentos  
	If Not isnull(Factores("BancoPopularSemanal").CodTipoDescuento) And cuota > 0.00 And liquido - cuota >= 0.00 Then       
	 agrega_descuentos_historial Agrupadores, _
								DescuentosEstaPlanilla, _
								Empleados.Fields("emp_codigo").Value, _
								Periodos.Fields("ppl_codigo").Value, _
								Factores("BancoPopularSemanal").CodTipoDescuento, _
								Round(cuota, 2), Round(patronal,2), afecto, Periodos.Fields("tpl_codmon").Value, _
								0.00, "Horas"
	End If
   
End If

BancoPopularSemanal = Round(cuota, 2)

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = '41be1aef-7cab-4178-b5df-2949a94c19fa';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('41be1aef-7cab-4178-b5df-2949a94c19fa','CreditoISRConyugeSemanal','El monto que se descuenta al ISR del empleado si tiene conyugüe','Function CreditoISRConyugeSemanal

valor = 0.00

If Empleados.Fields("aplica_isr_conyugue").Value Then
	valor = ParametrosAplicacion.Fields("isr_valor_conyugue").Value
End If

CreditoISRConyugeSemanal = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = 'af2e81c7-e63b-4dab-b7b9-a58d53e5d902';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('af2e81c7-e63b-4dab-b7b9-a58d53e5d902','CreditoISRHijosSemanal','El monto que se descuenta al ISR del empleado por el número de hijos que tiene','Function CreditoISRHijosSemanal

valor = 0.00

numHijos = Empleados.Fields("emp_numero_hijos").Value
valor = ParametrosAplicacion.Fields("isr_valor_hijos").Value * numHijos

CreditoISRHijosSemanal = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = '75933c24-8f2a-41fb-8428-2cd9005d23f3';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('75933c24-8f2a-41fb-8428-2cd9005d23f3','ISRSemanal','Determina el Monto a Descontar al Empleado por concepto de ISR Mensual','Function ISRSemanal()
	
If Periodos.Fields("ppl_es_ultima_semana").Value Then	
	
	afecto_anterior = 0.00
	afecto = 0.00
	porc = 0.00
	excedente = 0.00
	valor = 0.00
	liquido = 0.00

	liquido = Factores("TotalIngresos").Value - _
		Factores("SeguroSocial").Value - _
		Factores("BancoPopular").Value
	
	''monto afecto al impuesto sobre la renta
	If Not (IngresosPlanillaAnteriorISR.Bof And IngresosPlanillaAnteriorISR.Eof) Then
		afecto_anterior = IngresosPlanillaAnteriorISR.Fields("inn_valor").Value
	End If
	
	afecto = Round((Agrupadores("CRBaseCalculoRenta").Value + afecto_anterior), 2)
	
	''recorre la tabla para obtener el excedente y porcentaje correspondiente
	If Not (TablaISRMensual.Bof And TablaISRMensual.Eof) Then
		TablaISRMensual.MoveFirst
		
		Do Until TablaISRMensual.Eof Or valor > 0.00
			''calculo del ISR
			If afecto >= TablaISRMensual.Fields("inicio").Value And afecto <= TablaISRMensual.Fields("fin").Value Then
				excedente = TablaISRMensual.Fields("excedente").Value
				porc = TablaISRMensual.Fields("porcentaje").Value
				valor = ((afecto - TablaISRMensual.Fields("inicio").Value) * porc / 100.00) + excedente
			End If
			
			TablaISRMensual.MoveNext
		Loop	
	End If
	
	''resta el crédito por conyuges e hijos (si aplica)
	valor = valor - Factores("CreditoISRConyuge").Value - Factores("CreditoISRHijos").Value
	
	If valor < 0.00 Then 
		valor = 0.00
	End If
	
	If Not isnull(Factores("ISRSemanal").CodTipoDescuento) And valor > 0.00 And liquido - valor >= 0.00 Then       
		agrega_descuentos_historial Agrupadores, _
										DescuentosEstaPlanilla, _
										Empleados.Fields("emp_codigo").Value, _
										Periodos.Fields("ppl_codigo").Value, _
										Factores("ISRSemanal").CodTipoDescuento, _
										Round(valor, 2), 0.00, afecto, RubrosSalario.Fields("ese_codmon").Value, _
										0.00, "Horas"		
	End If
	
	ISRSemanal = valor	
	
End If

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = 'acb41acd-d1bc-4eb5-8f0a-ec25d31450a2';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('acb41acd-d1bc-4eb5-8f0a-ec25d31450a2','PensionAlimenticiaSemanal','Monto de descuentos cíclicos para la pensión alimenticia','Function PensionAlimenticiaSemanal

total = 0.00
valor = 0.00
liquido = 0.00
embargoMaximo = 0.00
porcMaxPension = ParametrosAplicacion.Fields("pal_porcentaje_maximo").Value

liquido = Factores("TotalIngresosSemanal").Value - _    
	Factores("SeguroSocialSemanal").Value - _
	Factores("DescuentoIncapacidadSemanal").Value - _	
	Factores("ISRSemanal").Value 

embargoMaximo = Factores("TotalIngresosSemanal").Value * porcMaxPension / 100.00

filtro = DescuentosCiclicos.Filter

DescuentosCiclicos.Filter = filtro & " And es_pension = 1"

If Not (DescuentosCiclicos.Bof And DescuentosCiclicos.Eof) Then
	DescuentosCiclicos.MoveFirst
	Do Until DescuentosCiclicos.Eof
	
		valor = Round(DescuentosCiclicos.Fields("cdc_valor_cobrado").Value, 2)
	
		If liquido - valor >= 0 And embargoMaximo - valor >= 0 Then
			liquido = liquido - valor
			embargoMaximo = embargoMaximo - valor
			total = total + valor
			DescuentosCiclicos.Fields("cdc_fecha_descuento").Value = Periodos.Fields("ppl_fecha_pago").Value
			DescuentosCiclicos.Fields("cdc_aplicado_planilla").Value = 1
	
			agrega_descuentos_historial Agrupadores, _
											DescuentosEstaPlanilla, _
											Empleados.Fields("emp_codigo").Value, _
											Periodos.Fields("ppl_codigo").Value, _
											DescuentosCiclicos.Fields("dcc_codtdc").Value, _
											valor, 0, 0, DescuentosCiclicos.Fields("dcc_codmon").Value, 0.00, "Horas"
		Else
			DescuentosCiclicos.Fields("cdc_aplicado_planilla").Value = 0
		End If
	    
		DescuentosCiclicos.MoveNext
	Loop 	
End If

DescuentosCiclicos.Filter = filtro

PensionAlimenticiaSemanal = total
	
End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = '87962b99-2a2f-4a42-9255-23efcc803a77';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('87962b99-2a2f-4a42-9255-23efcc803a77','PensionAlimenticiaPorcentajeSemanal','Monto de descuentos cíclicos por porcentaje para la pensión alimenticia','Function PensionAlimenticiaPorcentajeSemanal

total = 0.00
valor = 0.00
liquido = 0.00
afecto = 0.00
embargoMaximo = 0.00
porcMaxPension = ParametrosAplicacion.Fields("pal_porcentaje_maximo").Value

liquido = Round(Factores("TotalIngresosSemanal").Value - _		
	Factores("SeguroSocialSemanal").Value - _
	Factores("DescuentoIncapacidadSemanal").Value - _
	Factores("ISRSemanal").Value - _
	Factores("PensionAlimenticiaSemanal").Value, 2)

embargoMaximo = (Factores("TotalIngresosSemanal").Value * porcMaxPension / 100.00) - Factores("PensionAlimenticiaSemanal").Value

filtro = DescuentosCiclicosPorcentaje.Filter

DescuentosCiclicosPorcentaje.Filter = filtro & " And es_pension = 1"

If Not (DescuentosCiclicosPorcentaje.Bof And DescuentosCiclicosPorcentaje.Eof) Then

	DescuentosCiclicosPorcentaje.MoveFirst
	
	Do Until DescuentosCiclicosPorcentaje.Eof
		If DescuentosCiclicosPorcentaje.Fields("dcc_frecuencia_periodo_pla").Value = Periodos.Fields("ppl_frecuencia").Value Or _
			DescuentosCiclicosPorcentaje.Fields("dcc_frecuencia_periodo_pla").Value = "0" Then
			
			If ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) > 0.00 Then
	
				If DescuentosCiclicosPorcentaje.Fields("dcc_codagr").Value > 0 Then
					For i = 1 To Agrupadores.count
						If Agrupadores(i).codigo = DescuentosCiclicosPorcentaje.Fields("dcc_codagr").Value Then
	
							valor = Round(Agrupadores(i).Value * ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) / 100.00, 2)
		
							Exit For
						End If
					Next
				Else
					valor = ccur(Factores("SalarioActual").Value) * ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) / 100.00
				End If
				
				
				If valor > 0.00 And liquido - valor >= 0.00 And embargoMaximo - valor >= 0.00  Then
						liquido = ccur(liquido) - ccur(valor)
						embargoMaximo = embargoMaximo - valor
						total = total + valor
	
						agrega_descuentos_historial Agrupadores, _
												DescuentosEstaPlanilla, _
												Empleados.Fields("emp_codigo").Value, _
												Periodos.Fields("ppl_codigo").Value, _
												DescuentosCiclicosPorcentaje.Fields("dcc_codtdc").Value , _
												valor, 0.00, 0.00, DescuentosCiclicosPorcentaje.Fields("dcc_codmon").Value, 0.00, "Horas"
				End If
			End If
		End If
	   
		DescuentosCiclicosPorcentaje.MoveNext
	Loop		
End If

DescuentosCiclicosPorcentaje.Filter = filtro

PensionAlimenticiaPorcentajeSemanal = total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = 'b9ce70b9-3c49-43f3-a139-791b62f0796a';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('b9ce70b9-3c49-43f3-a139-791b62f0796a','EmbargoSemanal','Monto de descuentos cíclicos para el embargo','Function EmbargoSemanal

total = 0.00
valor = 0.00
liquido = 0.00
salarioEmbargable = 0.00
cargasSociales = 0.00
salarioInembargable = 0.00
embargoMaximo = 0.00
porcMenor = 0.00
porcMayor = 0.00
numSalMinimos = 0.00
total_ingresos = 0.00

liquido = Factores("TotalIngresosSemanal").Value - _
	Factores("SeguroSocialSemanal").Value - _
	Factores("BancoPopularSemanal").Value - _
	Factores("ISRSemanal").Value - _
	Factores("PensionAlimentariaSemanal").Value - _
	Factores("PensionAlimentariaPorcentajeSemanal").Value	

total_ingresos = Agrupadores("CRBaseCalculoEmbargo").Value

cargasSociales = Factores("TotalSeguroSocialQuincenal").Value + _
	Factores("TotalBancoPopularQuincenal").Value + _
	Factores("ISRQuincenal").Value

If Not (Embargos.Bof And Embargos.Eof) Then

	Embargos.MoveFirst
	
	Do Until Embargos.Eof
		
		salarioInembargable = Embargos.Fields("emb_salario_inembargable").Value / 4.33
		porcMenor = Embargos.Fields("emb_porcentaje_menor").Value / 100.00
		porcMayor = Embargos.Fields("emb_porcentaje_mayor").Value / 100.00
		numSalMinimos = Embargos.Fields("emb_salarios_minimos").Value
		saldo = Embargos.Fields("dcc_saldo").Value
		
		salarioEmbargable = total_ingresos - cargasSociales - 	salarioInembargable
		
		If salarioEmbargable > 0.00 And salarioEmbargable <= salarioInembargable * numSalMinimos Then
			embargoMaximo = Round(salarioEmbargable * porcMenor / 100.00, 2)
		Else
			embargoMaximo = Round((salarioInembargable * numSalMinimos * porcMenor / 100.00) + _
				((salarioEmbargable - (salarioInembargable * numSalMinimos)) * porcMayor / 100.00), 2)
		End If		
	
		If embargoMaximo > saldo Then
			valor = saldo
		Else
			valor = embargoMaximo
		End If

		If Not IsNull(Embargos.Fields("dcc_codtdc").Value) And liquido - valor >= 0.00 And valor > 0.00 Then
			agrega_descuentos_historial Agrupadores, _
											DescuentosEstaPlanilla, _
											Empleados.Fields("emp_codigo").Value, _
											Periodos.Fields("ppl_codigo").Value, _
											Embargos.Fields("dcc_codtdc").Value, _
											valor, 0.00, 0.00, Embargos.Fields("dcc_codmon").Value, 0.00, "Horas"
			
			Embargos.Fields("emb_salario_nominal").Value = salario_nominal
			Embargos.Fields("emb_cargas_sociales").Value = cargasSociales
			Embargos.Fields("emb_salario_embargable").Value = salarioEmbargable
			Embargos.Fields("emb_valor").Value = valor
			Embargos.Fields("emb_aplicado_planilla").Value = 1
			
			liquido = liquido - valor
			saldo = saldo - valor
			total = total + valor
		Else
			Embargos.Fields("emb_aplicado_planilla").Value = 0
		End If
		
		Embargos.MoveNext
	Loop	
End If

EmbargoSemanal  = total
	
End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = '04b38a2a-3acb-4dc5-9e2b-ffb018a6eb81';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('04b38a2a-3acb-4dc5-9e2b-ffb018a6eb81','SeguroMedicoSemanal','Determina el monto de Descuento por el Seguro Medico. Mensual','Function SeguroMedicoSemanal()

valor = 0.00
patronal = 0.00

liquido = Factores("TotalIngresosSemanal").Value - _
	Factores("SeguroSocialSemanal").Value - _
	Factores("BancoPopularSemanal").Value - _
	Factores("ISRSemanal").Value - _
	Factores("PensionAlimentariaSemanal").Value - _
	Factores("PensionAlimentariaPorcentajeSemanal").Value	- _
	Factores("EmbargoSemanal").Value		

If Not (SegurosMedicos.Bof And SegurosMedicos.Eof) Then
	patronal = SegurosMedicos.Fields("sem_cuota_patrono").Value 
	valor = SegurosMedicos.Fields("sem_cuota_empleado").Value 
End If

If Not IsNull(Factores("SeguroMedicoSemanal").CodTipoDescuento) And valor > 0 And liquido - valor > 0 Then       
	agrega_descuentos_historial Agrupadores, _
								DescuentosEstaPlanilla, _
								Empleados.Fields("emp_codigo").Value, _
								Periodos.Fields("ppl_codigo").Value, _
								Factores("SeguroMedicoSemanal").CodTipoDescuento, _
								Round(valor, 2), patronal, 0, Periodos.Fields("tpl_codmon").Value, 0, "Horas"
End If 

SeguroMedicoSemanal = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = '1e69acb9-0ccf-4da5-856f-a323de293656';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('1e69acb9-0ccf-4da5-856f-a323de293656','AsociacionSemanal','Valor por descuento de asociación','Function AsociacionSemanal

valor = 0.00
afecto = 0.00
total = 0.00
porcentaje = 0.00
liquido = 0.00

liquido = Factores("TotalIngresosSemanal").Value - _    
	Factores("SeguroSocialSemanal").Value - _         
	Factores("BancoPopularSemanal").Value - _		
	Factores("ISRSemanal").Value - _  
	Factores("PensionAlimenticiaSemanal").Value - _
	Factores("PensionAlimenticiaPorcentajeSemanal").Value - _
	Factores("EmbargoSemanal").Value - _
	Factores("SeguroMedicoSemanal").Value
	
afecto = Agrupadores("CRBaseCalculoAsociaciones").Value

If Not (Asociaciones.Bof And Asociaciones.Eof) Then
	Asociaciones.MoveFirst
	
	Do Until Asociaciones.Eof

		porcentaje = Asociaciones.Fields("ase_porcentaje_pago").Value / 100.00
		valor = afecto * porcentaje

		If Not IsNull(Asociaciones.Fields("ase_codtdc").Value) And liquido - valor >= 0 And valor > 0.00 Then
			agrega_descuentos_historial Agrupadores, _
											DescuentosEstaPlanilla, _
											Empleados.Fields("emp_codigo").Value, _
											Periodos.Fields("ppl_codigo").Value, _
											Asociaciones.Fields("ase_codtdc").Value, _
											valor, 0, 0, Periodos.Fields("tpl_codmon").Value, 0.00, "Horas"	
												
			total = total + valor
			liquido = liquido - valor
		
		End If
		
		Asociaciones.MoveNext
	Loop	
End If

AsociacionSemanal = total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = '866f1d72-ccd9-492a-be6b-a99d2a2a99fb';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('866f1d72-ccd9-492a-be6b-a99d2a2a99fb','DescuentoCiclicoSemanal','Determina el Monto a Descontar al empleado por Prestamos Mensual','Function DescuentoCiclicoSemanal

total = 0.00
valor = 0.00
liquido = 0.00

liquido = Factores("TotalIngresosSemanal").Value - _    
	Factores("SeguroSocialSemanal").Value - _         
	Factores("BancoPopularSemanal").Value - _		
	Factores("ISRSemanal").Value - _  
	Factores("PensionAlimenticiaSemanal").Value - _
	Factores("PensionAlimenticiaPorcentajeSemanal").Value - _
	Factores("EmbargoSemanal").Value - _
	Factores("SeguroMedicoSemanal").Value - _
	Factores("AsociacionSemanal").Value

filtro = DescuentosCiclicos.Filter

DescuentosCiclicos.Filter = filtro & " And es_pension = 0 And es_embargo = 0"

If Not (DescuentosCiclicos.Bof And DescuentosCiclicos.Eof) Then

	DescuentosCiclicos.MoveFirst

	Do Until DescuentosCiclicos.Eof
	
		valor = Round(DescuentosCiclicos.Fields("cdc_valor_cobrado").Value, 2)
	
		If (liquido - valor) > 0 Then
			liquido = liquido - valor
			total = total + valor
			DescuentosCiclicos.Fields("cdc_fecha_descuento").Value = Periodos.Fields("ppl_fecha_pago").Value
			DescuentosCiclicos.Fields("cdc_aplicado_planilla").Value = 1
	
			agrega_descuentos_historial Agrupadores, _
											DescuentosEstaPlanilla, _
											Empleados.Fields("emp_codigo").Value, _
											Periodos.Fields("ppl_codigo").Value, _
											DescuentosCiclicos.Fields("dcc_codtdc").Value, _
											valor, 0, 0, DescuentosCiclicos.Fields("dcc_codmon").Value, 0.00, "Horas"
		Else
			DescuentosCiclicos.Fields("cdc_aplicado_planilla").Value = 0
		End If
		
		DescuentosCiclicos.MoveNext
	Loop

End If

DescuentosCiclicos.Filter = filtro
	
DescuentoCiclicoSemanal = total
	
End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = '586d541e-886d-4afc-8cfc-69088e626338';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('586d541e-886d-4afc-8cfc-69088e626338','DescuentoCiclicoPorcentajeSemanal','Determina el Monto a Descontar al empleado por Prestamos Mensual','Function DescuentoCiclicoPorcentajeSemanal

total = 0.00
valor = 0.00
liquido = 0.00
afecto = 0.00

liquido = Factores("TotalIngresosSemanal").Value - _    
	Factores("SeguroSocialSemanal").Value - _         
	Factores("BancoPopularSemanal").Value - _		
	Factores("ISRSemanal").Value - _  
	Factores("PensionAlimenticiaSemanal").Value - _
	Factores("PensionAlimenticiaPorcentajeSemanal").Value - _
	Factores("EmbargoSemanal").Value - _
	Factores("SeguroMedicoSemanal").Value - _
	Factores("AsociacionSemanal").Value - _
	Factores("DescuentoCiclicoSemanal").Value

filtro = DescuentosCiclicosPorcentaje.Filter

DescuentosCiclicosPorcentaje.Filter = filtro & " And es_pension = 0 And es_embargo = 0"

If Not (DescuentosCiclicosPorcentaje.Bof And DescuentosCiclicosPorcentaje.Eof) Then

	DescuentosCiclicosPorcentaje.MoveFirst

	Do Until DescuentosCiclicosPorcentaje.Eof
	
		If ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) > 0.00 Then

			If DescuentosCiclicosPorcentaje.Fields("dcc_codagr").Value > 0 Then
				For i = 1 To Agrupadores.count
					If Agrupadores(i).codigo = DescuentosCiclicosPorcentaje.Fields("dcc_codagr").Value Then

						valor = Round(Agrupadores(i).Value * ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) / 100.00, 2)
	
						Exit For
					End If
				Next
			Else
				valor = ccur(Factores("SalarioActual").Value) * ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) / 100.00
			End If
			
			
			If valor > 0 Then
				If (ccur(liquido) - ccur(valor)) >= 0 Then
			
					liquido = ccur(liquido) - ccur(valor)
					total = total + valor

					agrega_descuentos_historial Agrupadores, _
											DescuentosEstaPlanilla, _
											Empleados.Fields("emp_codigo").Value, _
											Periodos.Fields("ppl_codigo").Value, _
											DescuentosCiclicosPorcentaje.Fields("dcc_codtdc").Value , _
											valor, 0.00, 0.00, DescuentosCiclicosPorcentaje.Fields("dcc_codmon").Value, 0.00, "Horas"
				End If
			End If
		End If
   
		DescuentosCiclicosPorcentaje.MoveNext
	Loop

End If

DescuentosCiclicosPorcentaje.Filter = filtro

DescuentoCiclicoPorcentajeSemanal = total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = 'ab6d8b70-f914-40d6-aad7-b3286b33e30f';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('ab6d8b70-f914-40d6-aad7-b3286b33e30f','DescuentoEventualSemanal','Determina el Monto a Descontar por Otros Descuentos al Empelado Mensual','Function DescuentoEventualSemanal()

valor = 0.00  
liquido = 0.00
total = 0.00

liquido = Factores("TotalIngresosSemanal").Value - _    
	Factores("SeguroSocialSemanal").Value - _         
	Factores("BancoPopularSemanal").Value - _		
	Factores("ISRSemanal").Value - _  
	Factores("PensionAlimenticiaSemanal").Value - _
	Factores("PensionAlimenticiaPorcentajeSemanal").Value - _
	Factores("EmbargoSemanal").Value - _
	Factores("SeguroMedicoSemanal").Value - _
	Factores("AsociacionSemanal").Value - _
	Factores("DescuentoCiclicoSemanal").Value - _
	Factores("DescuentoCiclicoPorcentajeSemanal").Value

If DescuentosEventuales.RecordCount > 0 Then
	DescuentosEventuales.MoveFirst
	Do Until DescuentosEventuales.Eof
		valor = Round(DescuentosEventuales.Fields("ods_valor_a_descontar").Value, 2)
   
		If liquido > 0.00 Then
			If valor > liquido Then
				liquido = 0
				total = total + liquido
				DescuentosEventuales.Fields("ods_aplicado_planilla").Value = 1
				agrega_descuentos_historial Agrupadores, _
												DescuentosEstaPlanilla, _
												Empleados.Fields("emp_codigo").Value, _
												Periodos.Fields("ppl_codigo").Value, _
												DescuentosEventuales.Fields("ods_codtdc").Value, _
												liquido, 0, 0, DescuentosEventuales.Fields("ods_codmon").Value, 0, "Horas"				
			Else
				liquido = liquido - valor
				total = total + valor
				DescuentosEventuales.Fields("ods_aplicado_planilla").Value = 1
				agrega_descuentos_historial Agrupadores, _
												DescuentosEstaPlanilla, _
												Empleados.Fields("emp_codigo").Value, _
												Periodos.Fields("ppl_codigo").Value, _
												DescuentosEventuales.Fields("ods_codtdc").Value, _
												valor, 0, 0, DescuentosEventuales.Fields("ods_codmon").Value, 0, "Horas"
			End If	
		Else
			DescuentosEventuales.Fields("ods_aplicado_planilla").Value = 0			
		End If
   
		DescuentosEventuales.MoveNext
	Loop
End If
 
DescuentoEventualSemanal = total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = 'df202fb6-966a-4cdc-af8f-01c53f3ed018';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('df202fb6-966a-4cdc-af8f-01c53f3ed018','TotalDescuentosSemanal','Total de descuentos del empleado','Function TotalDescuentosSemanal

TotalDescuentosSemanal = Round(Factores("TotalIngresosSemanal").Value + _    
	Factores("SeguroSocialSemanal").Value + _         
	Factores("BancoPopularSemanal").Value + _		
	Factores("ISRSemanal").Value + _  
	Factores("PensionAlimenticiaSemanal").Value + _
	Factores("PensionAlimenticiaPorcentajeSemanal").Value + _
	Factores("EmbargoSemanal").Value + _
	Factores("SeguroMedicoSemanal").Value + _
	Factores("AsociacionSemanal").Value + _
	Factores("DescuentoCiclicoSemanal").Value + _
	Factores("DescuentoCiclicoPorcentajeSemanal").Value + _
	Factores("DescuentoEventualSemanal").Value, 2)

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 26/02/2015 03:14 p.m. */

delete from sal.fac_factores where fac_codigo = 'd85c798f-4788-4ba3-b9e9-e19932efa854';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('d85c798f-4788-4ba3-b9e9-e19932efa854','NetoSemanal','Determina el Liquido a Percibir por el Empleado en el Periodo Mensual','Function NetoSemanal()

NetoSemanal = Round(Factores("TotalIngresosSemanal").Value - _
       Factores("TotalDescuentosSemanal").Value, 2)

End Function','money','cr',0);

COMMIT