/* Script generated by Evolution - FormulaEditor. 16/07/2014 03:58 p.m. */

begin transaction

delete sal.fat_factores_tipo_planilla where exists (select null from sal.tpl_tipo_planilla where tpl_codigo = fat_codtpl and tpl_codigo_visual in ('5', '6', '7', '8'));
delete sal.ftp_formulacion_tipos_planilla where exists (select null from sal.tpl_tipo_planilla where tpl_codigo = ftp_codtpl and tpl_codigo_visual in ('5', '6', '7', '8'));

/* Script generated by Evolution - FormulaEditor. 27/04/2015 04:09 p.m. */

begin transaction

delete from sal.fac_factores where fac_codigo = '6AA2D1E1-0245-47CE-8A9A-F624A04D8C59';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('6AA2D1E1-0245-47CE-8A9A-F624A04D8C59','FiltroEmpleadosAguinaldo','Determina que empleado participa en la planilla Aguinaldo','Function FiltroEmpleadosAguinaldo

FiltroEmpleadosAguinaldo = (EmpleadosAguinaldo.Fields("emp_fecha_ingreso").Value <= Periodos.Fields("ppl_fecha_fin").Value)

End Function','boolean','gt',0);

commit transaction;

/* Script generated by Evolution - FormulaEditor. 20/08/2014 12:33 p.m. */

delete from sal.fac_factores where fac_codigo = 'F5DF5DA7-E114-4B1A-9620-67FF44FA2C2F';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('F5DF5DA7-E114-4B1A-9620-67FF44FA2C2F','Aguinaldo','Valor Calculado de Aguinaldo','Function Aguinaldo()

valor = 0.00
dias = 0.00

If Not(CalculoAguinaldo.Bof And CalculoAguinaldo.Eof) Then
	
	valor = Round(CalculoAguinaldo.Fields("cag_valor").Value, 2)
	dias = CalculoAguinaldo.Fields("cag_dias").Value
	
	If Not IsNull(Factores("Aguinaldo").CodTipoIngreso) And valor > 0.00 Then    							
		agrega_ingresos_historial Agrupadores, _
									IngresosEstaPlanilla, _
									CalculoAguinaldo.Fields("cag_codemp").Value, _
									Periodos.Fields("ppl_codigo").Value, _
									Factores("Aguinaldo").CodTipoIngreso, _
									valor, 	Periodos.Fields("tpl_codmon").Value, dias, "Dias"
	End If

End If

Aguinaldo = valor

End Function','money','gt',0);

/* Script generated by Evolution - FormulaEditor. 20/08/2014 12:33 p.m. */

delete from sal.fac_factores where fac_codigo = 'E8C47224-8AE4-4280-AA2C-16031C4EBE51';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('E8C47224-8AE4-4280-AA2C-16031C4EBE51','IngresoEventualAguinaldo','Pago de Ingresos Eventuales Aguinaldo','Function IngresoEventualAguinaldo()

total = 0.00
valor = 0.00

If IngresosEventuales.RecordCount > 0 Then
	IngresosEventuales.MoveFirst
	
	Do Until IngresosEventuales.Eof
	
		valor = Round(IngresosEventuales.Fields("oin_valor_a_pagar").Value, 2)
		
		IngresosEventuales.Fields("oin_aplicado_planilla").Value = 1
		
		agrega_ingresos_historial Agrupadores, _
									IngresosEstaPlanilla, _
									EmpleadosAguinaldo.Fields("emp_codigo").Value, _
									Periodos.Fields("ppl_codigo").Value, _
									IngresosEventuales.Fields("oin_codtig").Value, _
									valor, IngresosEventuales.Fields("oin_codmon").Value, 0.00, "Dias"
									
		total = total + valor
		
		IngresosEventuales.MoveNext
	Loop
End If

IngresoEventualAguinaldo = total

End Function','money','gt',0);

/* Script generated by Evolution - FormulaEditor. 20/08/2014 12:33 p.m. */

delete from sal.fac_factores where fac_codigo = 'F85BCB44-0DAD-4408-848D-2D5D305234B5';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('F85BCB44-0DAD-4408-848D-2D5D305234B5','TotalIngresosAguinaldo','Suma de Todos los Ingresos Devengados por el Empleado en el periodo Aguinaldo','Function TotalIngresosAguinaldo()

valor = 0       

valor = Round(Factores("Aguinaldo").Value + _          	  
			   Factores("IngresoEventualAguinaldo").Value, 2) 

TotalIngresosAguinaldo = valor

End Function','money','gt',0);

/* Script generated by Evolution - FormulaEditor. 20/08/2014 12:33 p.m. */

delete from sal.fac_factores where fac_codigo = '481C6FB9-2A0E-474F-9682-F21B23E8FA51';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('481C6FB9-2A0E-474F-9682-F21B23E8FA51','DescuentoEventualAguinaldo','Determina el Monto a Descontar por Otros Descuentos al Empelado Aguinaldo','Function DescuentoEventualAguinaldo()

valor = 0.00  
liquido = 0.00
total = 0.00

liquido = Round(Factores("TotalIngresosAguinaldo").Value - _
	Factores("PensionAlimenticiaAguinaldo").Value - _
	Factores("PensionAlimenticiaPorcentajeAguinaldo").Value, 2)

If DescuentosEventuales.RecordCount > 0 Then
	DescuentosEventuales.MoveFirst
	Do Until DescuentosEventuales.Eof
		valor = Round(DescuentosEventuales.Fields("ods_valor_a_descontar").Value, 2)
   
		If valor > liquido Then
			DescuentosEventuales.Fields("ods_aplicado_planilla").Value = 0
		Else
			liquido = liquido - valor
			total = total + valor
			DescuentosEventuales.Fields("ods_aplicado_planilla").Value = 1
			agrega_descuentos_historial Agrupadores, _
											DescuentosEstaPlanilla, _
											EmpleadosAguinaldo.Fields("emp_codigo").Value, _
											Periodos.Fields("ppl_codigo").Value, _
											DescuentosEventuales.Fields("ods_codtdc").Value, _
											valor, 0, 0, DescuentosEventuales.Fields("ods_codmon").Value, 0.00, "Dias"
		End If
   
		DescuentosEventuales.MoveNext
	Loop
End If
 
DescuentoEventualAguinaldo = total

End Function','money','gt',0);

/* Script generated by Evolution - FormulaEditor. 20/08/2014 12:33 p.m. */

delete from sal.fac_factores where fac_codigo = '114C4EB5-0A98-4550-B685-E4114753ECF6';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('114C4EB5-0A98-4550-B685-E4114753ECF6','NetoAguinaldo','Determina el Liquido a Percibir por el Empleado en el Periodo Aguinaldo','Function NetoAguinaldo()

NetoAguinaldo = Round(Factores("TotalIngresosAguinaldo").Value - _
						Factores("TotalDescuentosAguinaldo").Value, 2)

End Function','money','gt',0);

/* Script generated by Evolution - FormulaEditor. 20/08/2014 12:33 p.m. */

delete from sal.fac_factores where fac_codigo = 'a4bcd369-48b6-40da-8926-b0bc58d87cf3';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('a4bcd369-48b6-40da-8926-b0bc58d87cf3','PensionAlimenticiaAguinaldo','Monto de descuentos cíclicos para la pensión alimenticia','Function PensionAlimenticiaAguinaldo

total = 0.00
valor = 0.00
liquido = 0.00
embargoMaximo = 0.00
porcMaxPension = ParametrosAplicacion.Fields("pal_porcentaje_maximo").Value

liquido = Factores("TotalIngresosAguinaldo").Value

embargoMaximo = Factores("TotalIngresosAguinaldo").Value * porcMaxPension / 100.00

filtro = DescuentosCiclicos.Filter

DescuentosCiclicos.Filter = filtro & " And es_pension = 1"

If Not (DescuentosCiclicos.Bof And DescuentosCiclicos.Eof) Then
	DescuentosCiclicos.MoveFirst
	Do Until DescuentosCiclicos.Eof
	
		valor = Round(DescuentosCiclicos.Fields("cdc_valor_cobrado").Value, 2)
	
		If liquido - valor >= 0 And embargoMaximo - valor >= 0 Then
			liquido = liquido - valor
			embargoMaximo = embargoMaximo - valor
			total = total + valor
			DescuentosCiclicos.Fields("cdc_fecha_descuento").Value = Periodos.Fields("ppl_fecha_pago").Value
			DescuentosCiclicos.Fields("cdc_aplicado_planilla").Value = 1
	
			agrega_descuentos_historial Agrupadores, _
											DescuentosEstaPlanilla, _
											EmpleadosAguinaldo.Fields("emp_codigo").Value, _
											Periodos.Fields("ppl_codigo").Value, _
											DescuentosCiclicos.Fields("dcc_codtdc").Value, _
											valor, 0, 0, DescuentosCiclicos.Fields("dcc_codmon").Value, 0.00, "Dias"
		Else
			DescuentosCiclicos.Fields("cdc_aplicado_planilla").Value = 0
		End If
	    
		DescuentosCiclicos.MoveNext
	Loop 	
End If

DescuentosCiclicos.Filter = filtro

PensionAlimenticiaAguinaldo = total
	
End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 20/08/2014 12:33 p.m. */

delete from sal.fac_factores where fac_codigo = '57c6bb8f-7577-4c38-967c-1c73f3619ec3';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('57c6bb8f-7577-4c38-967c-1c73f3619ec3','PensionAlimenticiaPorcentajeAguinaldo','Monto de descuentos cíclicos por porcentaje para la pensión alimenticia','Function PensionAlimenticiaPorcentajeAguinaldo

total = 0.00
valor = 0.00
liquido = 0.00
afecto = 0.00
embargoMaximo = 0.00
porcMaxPension = ParametrosAplicacion.Fields("pal_porcentaje_maximo").Value

liquido = Round(Factores("TotalIngresosAguinaldo").Value - _
	Factores("PensionAlimenticiaAguinaldo").Value, 2)

embargoMaximo = (Factores("TotalIngresosAguinaldo").Value * porcMaxPension / 100.00) - Factores("PensionAlimenticiaAguinaldo").Value

filtro = DescuentosCiclicosPorcentaje.Filter

DescuentosCiclicosPorcentaje.Filter = filtro & " And es_pension = 1"

If Not (DescuentosCiclicosPorcentaje.Bof And DescuentosCiclicosPorcentaje.Eof) Then

	DescuentosCiclicosPorcentaje.MoveFirst
	
	Do Until DescuentosCiclicosPorcentaje.Eof
		If DescuentosCiclicosPorcentaje.Fields("dcc_frecuencia_periodo_pla").Value = Periodos.Fields("ppl_frecuencia").Value Or _
			DescuentosCiclicosPorcentaje.Fields("dcc_frecuencia_periodo_pla").Value = "0" Then
			
			If ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) > 0.00 Then
	
				If DescuentosCiclicosPorcentaje.Fields("dcc_codagr").Value > 0 Then
					For i = 1 To Agrupadores.count
						If Agrupadores(i).codigo = DescuentosCiclicosPorcentaje.Fields("dcc_codagr").Value Then
	
							valor = Round(Agrupadores(i).Value * ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) / 100.00, 2)
		
							Exit For
						End If
					Next
				Else
					valor = ccur(Factores("Aguinaldo").Value) * ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) / 100.00
				End If
				
				
				If valor > 0.00 And liquido - valor >= 0.00 And embargoMaximo - valor >= 0.00  Then
						liquido = ccur(liquido) - ccur(valor)
						embargoMaximo = embargoMaximo - valor
						total = total + valor
	
						agrega_descuentos_historial Agrupadores, _
												DescuentosEstaPlanilla, _
												EmpleadosAguinaldo.Fields("emp_codigo").Value, _
												Periodos.Fields("ppl_codigo").Value, _
												DescuentosCiclicosPorcentaje.Fields("dcc_codtdc").Value , _
												valor, 0.00, 0.00, DescuentosCiclicosPorcentaje.Fields("dcc_codmon").Value, 0.00, "Dias"
				End If
			End If
		End If
	   
		DescuentosCiclicosPorcentaje.MoveNext
	Loop		
End If

DescuentosCiclicosPorcentaje.Filter = filtro

PensionAlimenticiaPorcentajeAguinaldo = total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 20/08/2014 12:33 p.m. */

delete from sal.fac_factores where fac_codigo = 'b2c977a5-270a-4458-9b4d-30a6b000bd4b';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('b2c977a5-270a-4458-9b4d-30a6b000bd4b','TotalDescuentosAguinaldo','Total de descuentos en el aguinaldo','Function TotalDescuentosAguinaldo

valor = 0.00     

valor = Round(Factores("PensionAlimenticiaAguinaldo").Value + _          	  
			   Factores("PensionAlimenticiaPorcentajeAguinaldo").Value + _
			   Factores("DescuentoEventualAguinaldo").Value, 2) 

TotalDescuentosAguinaldo = valor

End Function','money','cr',0);

commit transaction;
