BEGIN TRANSACTION

DELETE sal.fat_factores_tipo_planilla WHERE EXISTS (SELECT NULL FROM sal.tpl_tipo_planilla WHERE tpl_codigo = fat_codtpl AND tpl_codigo_visual IN ('9', '10'))
DELETE sal.ftp_formulacion_tipos_planilla WHERE EXISTS (SELECT NULL FROM sal.tpl_tipo_planilla WHERE tpl_codigo = ftp_codtpl AND tpl_codigo_visual IN ('9', '10'))

/* Script generated by Evolution - FormulaEditor. 19/02/2015 12:30 p.m. */

delete from sal.fac_factores where fac_codigo = '3f8d9381-f4c5-48f8-8d6e-fc2763890f16';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('3f8d9381-f4c5-48f8-8d6e-fc2763890f16','BancoPopularExtraordinaria','Valor del descuento de banco popular','Function BancoPopularExtraordinaria()

afecto = 0.00
cuota = 0.00
por_cuota = 0.00
liquido = Factores("TotalIngresosExtraordinaria").Value - _
	Factores("SeguroSocialExtraordinaria").Value

If EmpleadosExtraordinaria.Fields("aplica_banco_popular").Value Then
	
	por_cuota = ParametrosAplicacion.Fields("banco_popular_porcentaje").Value

	afecto = Agrupadores("CRBaseCalculoBP").Value
  
	cuota = por_cuota / 100.00 * afecto
	
	If cuota < 0.00 Then 
		cuota = 0.00       
	End If
	
	'' inserta el registro en la tabla de descuentos  
	If Not isnull(Factores("BancoPopularExtraordinaria").CodTipoDescuento) And cuota > 0.00 And liquido - cuota >= 0.00 Then       
	 agrega_descuentos_historial Agrupadores, _
								DescuentosEstaPlanilla, _
								EmpleadosExtraordinaria.Fields("emp_codigo").Value, _
								Periodos.Fields("ppl_codigo").Value, _
								Factores("BancoPopularExtraordinaria").CodTipoDescuento, _
								Round(cuota, 2), Round(patronal,2), afecto, Periodos.Fields("tpl_codmon").Value, _
								0.00, "Dias"
	End If
   
End If

BancoPopularExtraordinaria = Round(cuota, 2)

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 19/02/2015 12:30 p.m. */

delete from sal.fac_factores where fac_codigo = 'b0b05405-9be6-43cb-8a53-9e434a182f42';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('b0b05405-9be6-43cb-8a53-9e434a182f42','DescuentoEventualExtraordinaria','Determina el Monto a Descontar por Otros Descuentos al Empelado Mensual','Function DescuentoEventualExtraordinaria()

valor = 0.00  
liquido = 0.00
total = 0.00

liquido = Factores("TotalIngresosExtraordinaria").Value - _
	Factores("SeguroSocialExtraordinaria").Value - _
	Factores("BancoPopularExtraordinaria").Value - _	
	Factores("ISRExtraordinaria").Value

If DescuentosEventuales.RecordCount > 0 Then
	DescuentosEventuales.MoveFirst
	Do Until DescuentosEventuales.Eof
		valor = Round(DescuentosEventuales.Fields("ods_valor_a_descontar").Value, 2)
   
		If valor > liquido Then
			DescuentosEventuales.Fields("ods_aplicado_planilla").Value = 0
		Else
			liquido = liquido - valor
			total = total + valor
			DescuentosEventuales.Fields("ods_aplicado_planilla").Value = 1
			agrega_descuentos_historial Agrupadores, _
											DescuentosEstaPlanilla, _
											EmpleadosExtraordinaria.Fields("emp_codigo").Value, _
											Periodos.Fields("ppl_codigo").Value, _
											DescuentosEventuales.Fields("ods_codtdc").Value, _
											valor, 0, 0, DescuentosEventuales.Fields("ods_codmon").Value, 0, "Dias"
		End If
   
		DescuentosEventuales.MoveNext
	Loop
End If
 
DescuentoEventualExtraordinaria = total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 19/02/2015 12:30 p.m. */

delete from sal.fac_factores where fac_codigo = '76f8f467-00df-4f43-8323-b4aeccff64cd';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('76f8f467-00df-4f43-8323-b4aeccff64cd','ExtraordinarioExtraordinaria','Determina el Monto devengado el empleado por Horas Extras Mensual','Function ExtraordinarioExtraordinaria()

valor = 0.00
total = 0.00
horas = 0

If HorasExtras.RecordCount > 0 Then
  
  HorasExtras.MoveFirst

  Do Until HorasExtras.Eof

	valor = Round(HorasExtras.Fields("ext_valor_a_pagar").Value, 2)
	
	horas = Round(HorasExtras.Fields("ext_num_horas").Value, 2)
	
	total = total + valor
	
	HorasExtras.Fields("ext_aplicado_planilla").Value = 1
	
	If Not IsNull(HorasExtras.Fields("the_codtig").Value) And valor > 0.00 Then
   		agrega_ingresos_historial Agrupadores, _
								IngresosEstaPlanilla, _
								EmpleadosExtraordinaria.Fields("emp_codigo").Value, _
								Periodos.Fields("ppl_codigo").Value, _
								HorasExtras.Fields("the_codtig").Value, _
								Round(valor, 2), _
								Periodos.Fields("tpl_codmon").Value, _
								Round(horas, 2), "Horas"		
	End If
	
	HorasExtras.MoveNext
  Loop

End If

ExtraordinarioExtraordinaria = total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 19/02/2015 12:30 p.m. */

delete from sal.fac_factores where fac_codigo = '4fa04322-896f-47ad-8bf6-2ba76cc1e9f9';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('4fa04322-896f-47ad-8bf6-2ba76cc1e9f9','FiltroEmpleadosExtraordinaria','Determina que empleado participa en la planilla','Function FiltroEmpleadosExtraordinaria()

FiltroEmpleadosExtraordinaria = (EmpleadosExtraordinaria.Fields("emp_fecha_ingreso").Value <= Periodos.Fields("ppl_fecha_fin").Value)

End Function ','boolean','cr',0);

/* Script generated by Evolution - FormulaEditor. 19/02/2015 12:30 p.m. */

delete from sal.fac_factores where fac_codigo = '8231cb96-25eb-47c3-abc0-9cb6e3375ba5';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('8231cb96-25eb-47c3-abc0-9cb6e3375ba5','IngresoEventualExtraordinaria','Pago de Ingresos Eventuales Mensual','Function IngresoEventualExtraordinaria()

total = 0.00
valor = 0.00

If IngresosEventuales.RecordCount > 0 Then
	IngresosEventuales.MoveFirst
	
	Do Until IngresosEventuales.Eof
	
		valor = Round(IngresosEventuales.Fields("oin_valor_a_pagar").Value, 2)
		
		IngresosEventuales.Fields("oin_aplicado_planilla").Value = 1
		
		agrega_ingresos_historial Agrupadores, _
									IngresosEstaPlanilla, _
									EmpleadosExtraordinaria.Fields("emp_codigo").Value, _
									Periodos.Fields("ppl_codigo").Value, _
									IngresosEventuales.Fields("oin_codtig").Value, _
									valor, IngresosEventuales.Fields("oin_codmon").Value, 0.00, "Dias"
									
		total = total + valor
		
		IngresosEventuales.MoveNext
	Loop
End If

IngresoEventualExtraordinaria = total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 19/02/2015 12:30 p.m. */

delete from sal.fac_factores where fac_codigo = '078c36ef-c1c2-4c40-9362-0d4eab869f3d';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('078c36ef-c1c2-4c40-9362-0d4eab869f3d','ISRExtraordinaria','Determina el Monto a Descontar al Empleado por concepto de ISR Mensual','Function ISRExtraordinaria()
	
afecto = 0.00
porc = 0.00
excedente = 0.00
valor = 0.00
liquido = 0.00
tasa_cambio = 0.00

liquido = Factores("TotalIngresosExtraordinaria").Value - _
	Factores("SeguroSocialExtraordinaria").Value - _
	Factores("BancoPopularExtraordinaria").Value
	
tasa_cambio = ParametrosAplicacion.Fields("tasa_cambio").Value		

afecto = Round((Agrupadores("CRBaseCalculoRenta").Value) * tasa_cambio, 2)

''recorre la tabla para obtener el excedente y porcentaje correspondiente
If Not (TablaISRMensual.Bof And TablaISRMensual.Eof) Then
	TablaISRMensual.MoveFirst
	
	Do Until TablaISRMensual.Eof Or valor > 0.00
		''calculo del ISR
		If afecto >= TablaISRMensual.Fields("inicio").Value And afecto <= TablaISRMensual.Fields("fin").Value Then
			excedente = TablaISRMensual.Fields("excedente").Value
			porc = TablaISRMensual.Fields("porcentaje").Value
			valor = ((afecto - TablaISRMensual.Fields("inicio").Value) * porc / 100.00) + excedente
		End If
		
		TablaISRMensual.MoveNext
	Loop	
End If

''resta el crédito por conyuges e hijos (si aplica)
valor = valor / tasa_cambio

If valor < 0.00 Then 
	valor = 0.00
End If

If Not IsNull(Factores("ISRExtraordinaria").CodTipoDescuento) And valor > 0.00 And liquido - valor >= 0.00 Then       
	agrega_descuentos_historial Agrupadores, _
									DescuentosEstaPlanilla, _
									EmpleadosExtraordinaria.Fields("emp_codigo").Value, _
									Periodos.Fields("ppl_codigo").Value, _
									Factores("ISRExtraordinaria").CodTipoDescuento, _
									Round(valor, 2), 0.00, afecto, RubrosSalario.Fields("ese_codmon").Value, _
									0.00, "Dias"		
End If

ISRExtraordinaria = valor	

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 19/02/2015 12:30 p.m. */

delete from sal.fac_factores where fac_codigo = '65cf6909-ce86-4828-82c1-04f95dd56b6f';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('65cf6909-ce86-4828-82c1-04f95dd56b6f','NetoExtraordinaria','Determina el Liquido a Percibir por el Empleado en el Periodo Mensual','Function NetoExtraordinaria()

NetoExtraordinaria = Factores("TotalIngresosExtraordinaria").Value - _
       Factores("TotalDescuentosExtraordinaria").Value

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 19/02/2015 12:30 p.m. */

delete from sal.fac_factores where fac_codigo = '02bfaff3-34c4-4839-ac0b-ff8df997f6be';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('02bfaff3-34c4-4839-ac0b-ff8df997f6be','SeguroSocialExtraordinaria','Determina el Monto a Descontar por concepto de IGSS al empleado en el periodo Mensual','Function SeguroSocialExtraordinaria()

afecto = 0.00
cuota = 0.00
patronal = 0.00
por_cuota = 0.00
pat_cuota = 0.00
codtdc = 0
liquido = Factores("TotalIngresosExtraordinaria").Value

If EmpleadosExtraordinaria.Fields("aplica_seguro_social").Value Then
	
	If EmpleadosExtraordinaria.Fields("emp_es_jubilado").Value Then
		por_cuota = ParametrosAplicacion.Fields("porc_jubilado_seguro_social").Value
		codtdc = ParametrosAplicacion.Fields("codtdc_ccss_jubilado").Value
	Else
		por_cuota = ParametrosAplicacion.Fields("porc_empleado_seguro_social").Value
		codtdc = ParametrosAplicacion.Fields("codtdc_ccss").Value
	End If
	
	pat_cuota = ParametrosAplicacion.Fields("porc_patrono_seguro_social").Value

	afecto = Agrupadores("CRBaseCalculoCCSS").Value
  
	cuota = por_cuota / 100.00 * afecto
	
	If cuota < 0.00 Then 
		cuota = 0.00       
	End If
	
	patronal = Round(pat_cuota / 100.00 * afecto,2)
	
	If patronal < 0.00 Then  
		patronal = 0.00  
	End If                                   
	
	'' inserta el registro en la tabla de descuentos  
	If codtdc > 0 And cuota > 0.00 And liquido - cuota >= 0.00 Then       
	 agrega_descuentos_historial Agrupadores, _
								DescuentosEstaPlanilla, _
								EmpleadosExtraordinaria.Fields("emp_codigo").Value, _
								Periodos.Fields("ppl_codigo").Value, _
								codtdc, _
								Round(cuota, 2), Round(patronal,2), afecto, Periodos.Fields("tpl_codmon").Value, _
								0.00, "Dias"
	End If
   
End If

SeguroSocialExtraordinaria = Round(cuota, 2)

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 19/02/2015 12:30 p.m. */

delete from sal.fac_factores where fac_codigo = '91571d54-bb8c-4903-ada7-653bff9b7bf5';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('91571d54-bb8c-4903-ada7-653bff9b7bf5','TotalDescuentosExtraordinaria','Total de descuentos del empleado','Function TotalDescuentosExtraordinaria

TotalDescuentosExtraordinaria = Round(Factores("SeguroSocialExtraordinaria").Value + _
	Factores("BancoPopularExtraordinaria").Value + _
	Factores("ISRExtraordinaria").Value + _
	Factores("DescuentoEventualExtraordinaria").Value, 2)

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 19/02/2015 12:30 p.m. */

delete from sal.fac_factores where fac_codigo = '6b25667a-4cfc-4d23-8273-781dea145360';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('6b25667a-4cfc-4d23-8273-781dea145360','TotalIngresosExtraordinaria','Suma de Todos los Ingresos Devengados por el Empleado en el periodo Mensual','Function TotalIngresosExtraordinaria()

valor = 0.00

valor = Round(Factores("ExtraordinarioExtraordinaria").Value + _          
              Factores("IngresoEventualExtraordinaria").Value, 2) 

TotalIngresosExtraordinaria = valor

End Function','money','cr',0);

COMMIT