BEGIN TRANSACTION

DELETE sal.fat_factores_tipo_planilla WHERE EXISTS (SELECT NULL FROM sal.tpl_tipo_planilla WHERE tpl_codigo = fat_codtpl AND tpl_codigo_visual IN ('1'))
DELETE sal.ftp_formulacion_tipos_planilla WHERE EXISTS (SELECT NULL FROM sal.tpl_tipo_planilla WHERE tpl_codigo = ftp_codtpl AND tpl_codigo_visual IN ('1'))

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '814219DD-1ED1-415F-BCAD-2ACFC7B3AB6B';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('814219DD-1ED1-415F-BCAD-2ACFC7B3AB6B','TotalIngresos','Suma de Todos los Ingresos Devengados por el Empleado en el periodo Mensual','Function TotalIngresos()

valor = 0.00

valor = Round(Factores("Salario").Value + _        
              Factores("BonoPactado").Value + _   
              Factores("Extraordinario").Value + _          
              Factores("RetroactivoSalario").Value + _
              Factores("RetroactivoBonoPactado").Value + _
              Factores("ComplementoSalario").Value + _                
              Factores("ComplementoBonoPactado").Value + _                
              Factores("PrestacionEmpleado").Value + _
              Factores("PrestacionIncapacidad").Value + _	 		  
              Factores("Vacacion").Value + _
              Factores("BonoVacacional").Value + _
              Factores("IngresoCiclico").Value + _
              Factores("IngresoEventual").Value + _
              Factores("Sustitucion").Value, 2) 
              

TotalIngresos = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'A5161DEB-42C0-4E0E-8175-84ACDC79C626';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('A5161DEB-42C0-4E0E-8175-84ACDC79C626','IngresoEventual','Pago de Ingresos Eventuales Mensual','Function IngresoEventual()

total = 0.00
valor = 0.00
 
If Periodos.Fields("ppl_frecuencia").Value = 2 Then	

	If IngresosEventuales.RecordCount > 0 Then
		IngresosEventuales.MoveFirst
		
		Do Until IngresosEventuales.Eof
		
			valor = Round(IngresosEventuales.Fields("oin_valor_a_pagar").Value, 2)
			
			IngresosEventuales.Fields("oin_aplicado_planilla").Value = 1
			
			agrega_ingresos_historial Agrupadores, _
										IngresosEstaPlanilla, _
										Empleados.Fields("emp_codigo").Value, _
										Periodos.Fields("ppl_codigo").Value, _
										IngresosEventuales.Fields("oin_codtig").Value, _
										valor, IngresosEventuales.Fields("oin_codmon").Value, 0.00, "Dias"
										
			total = total + valor
			
			IngresosEventuales.MoveNext
		Loop
	End If
	
End If

IngresoEventual = total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '97DF903D-46A1-477D-921F-8E325484FF3C';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('97DF903D-46A1-477D-921F-8E325484FF3C','DiasNoTrabajados','Obtiene el Tiempo No Trabajado por el Empleado Mensual','Function DiasNoTrabajados()

dias = 0  

If TiemposNoTrabajados.RecordCount > 0 Then         
	
	TiemposNoTrabajados.MoveFirst         
	
	Do While Not TiemposNoTrabajados.Eof              

		dias = dias + TiemposNoTrabajados.Fields("dias").Value 

		TiemposNoTrabajados.MoveNext  
		
	Loop         

End If             

DiasNoTrabajados = dias  

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'BEFA07C4-F284-4DF6-8B76-57417CD8A65A';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('BEFA07C4-F284-4DF6-8B76-57417CD8A65A','Extraordinario','Determina el Monto devengado el empleado por Horas Extras Mensual','Function Extraordinario()

valor = 0.00
horas = 0

If Periodos.Fields("ppl_frecuencia").Value = 2 Then 

   If HorasExtras.RecordCount > 0 Then
      
      HorasExtras.MoveFirst
	
      Do Until HorasExtras.Eof

         valor = valor + Round(HorasExtras.Fields("ext_valor_a_pagar").Value, 2)
         
         horas = horas + Round(HorasExtras.Fields("ext_num_horas").Value, 2)
         
         HorasExtras.Fields("ext_aplicado_planilla").Value = 1

         HorasExtras.MoveNext
      Loop
	
      If Not IsNull(Factores("Extraordinario").CodTipoIngreso) And valor > 0.00 Then
	   		agrega_ingresos_historial Agrupadores, _
									IngresosEstaPlanilla, _
									Empleados.Fields("emp_codigo").Value, _
									Periodos.Fields("ppl_codigo").Value, _
									Factores("Extraordinario").CodTipoIngreso, _
									Round(valor, 2), _
									Periodos.Fields("tpl_codmon").Value, _
									Round(horas, 2), "Horas"
      End If

   End If

End If

Extraordinario = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '26322A5C-2E2C-4E43-B245-9795A8EC2B24';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('26322A5C-2E2C-4E43-B245-9795A8EC2B24','SalarioActual','Determina la parte del Salario Nominal del Empleado Mensual','Function SalarioActual()

valor = 0.00

'' Calcula Salario Actual
If Not (RubrosSalario.Bof And RubrosSalario.Eof) Then
	If IsNull(RubrosSalario.Fields("ese_valor").Value ) Then
		valor = 0
	Else
		If RubrosSalario.Fields("ese_exp_valor").Value = "Diario" Then
			valor = RubrosSalario.Fields("ese_valor").Value * 30
		Else
			valor = RubrosSalario.Fields("ese_valor").Value
		End If
	End If
End If
   
SalarioActual = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '61281C0E-9C67-440B-9C1B-DC0BAE7397BD';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('61281C0E-9C67-440B-9C1B-DC0BAE7397BD','DescuentoCiclico','Determina el Monto a Descontar al empleado por Prestamos Mensual','Function DescuentoCiclico

total = 0.00
valor = 0.00
liquido = 0.00

If Periodos.Fields("ppl_frecuencia").Value = 2 Then	

	liquido = Factores("TotalIngresos").Value - _    
		Factores("DescuentoAnticipo").Value - _
		Factores("SeguroSocial").Value - _            
		Factores("ISR").Value - _  
		Factores("PensionAlimenticia").Value - _
		Factores("PensionAlimenticiaPorcentaje").Value - _
		Factores("Embargo").Value - _
		Factores("EmbargoPorcentaje").Value - _
		Factores("SeguroMedico").Value
	
	filtro = DescuentosCiclicos.Filter
	
	DescuentosCiclicos.Filter = filtro & " And es_pension = 0 And es_embargo = 0"
	
	If Not (DescuentosCiclicos.Bof And DescuentosCiclicos.Eof) Then
	
		DescuentosCiclicos.MoveFirst
	
		Do Until DescuentosCiclicos.Eof
		
			valor = Round(DescuentosCiclicos.Fields("cdc_valor_cobrado").Value, 2)
		
			If (liquido - valor) > 0 Then
				liquido = liquido - valor
				total = total + valor
				DescuentosCiclicos.Fields("cdc_fecha_descuento").Value = Periodos.Fields("ppl_fecha_pago").Value
				DescuentosCiclicos.Fields("cdc_aplicado_planilla").Value = 1
		
				agrega_descuentos_historial Agrupadores, _
												DescuentosEstaPlanilla, _
												Empleados.Fields("emp_codigo").Value, _
												Periodos.Fields("ppl_codigo").Value, _
												DescuentosCiclicos.Fields("dcc_codtdc").Value, _
												valor, 0, 0, DescuentosCiclicos.Fields("dcc_codmon").Value, 0, "dias"
			Else
				DescuentosCiclicos.Fields("cdc_aplicado_planilla").Value = 0
			End If
			
			DescuentosCiclicos.MoveNext
		Loop
	
	End If
	
	DescuentosCiclicos.Filter = filtro
	
End If	
	
	DescuentoCiclico = total
	
End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '138584C5-182B-407A-834E-1CACD3726900';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('138584C5-182B-407A-834E-1CACD3726900','FiltroEmpleados','Determina que empleado participa en la planilla','Function FiltroEmpleados()

FiltroEmpleados = (Empleados.Fields("emp_fecha_ingreso").Value <= Periodos.Fields("ppl_fecha_fin").Value) And Empleados.Fields("emp_codtpl").Value = Periodos.Fields("ppl_codtpl").Value

End Function ','boolean','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'D258CE6A-AFAB-4F7D-A199-D747A894F218';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('D258CE6A-AFAB-4F7D-A199-D747A894F218','BonoVacacional','Monto de Bono por vacaciones gozadas Mensual','Function BonoVacacional()

montobono = 0.00
diasbono = 0
valor_total = 0.00
dias_total = 0

If Periodos.Fields("ppl_frecuencia").Value = 2 Then	

	If Vacaciones.RecordCount > 0 Then
		
		Vacaciones.MoveFirst
	
		If Not (Vacaciones.Bof And Vacaciones.Eof) Then 
		
			Do While Not Vacaciones.Eof   
			
			diasbono = CDbl(Vacaciones.Fields("vca_dias_gozados").Value)
			montobono = CDbl(Vacaciones.Fields("vca_valor_bono").Value)
			
			dias_total = dias_total + diasbono
			valor_total = valor_total + montobono
			
			Vacaciones.MoveNext
			
			Loop
		End If
	End If
	
	If Not IsNull(Factores("BonoVacacional").CodTipoIngreso) And valor_total > 0 Then
	      agrega_ingresos_historial Agrupadores, _
	                                IngresosEstaPlanilla, _
	                                Empleados.Fields("emp_codigo").Value, _
	                                Periodos.Fields("ppl_codigo").Value, _
	                                Factores("BonoVacacional").CodTipoIngreso, _
	                                valor_total, RubrosSalario.Fields("ese_codmon").Value, dias_total, "Dias"
	
	End If

End If

BonoVacacional= valor_total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '38BF0B7A-152F-4798-BD8A-099939CB84B8';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('38BF0B7A-152F-4798-BD8A-099939CB84B8','RetroactivoSalario','Determina el valor del Retroactivo de Incremento sobre Salario Otorgado al Empleado Mensual','Function RetroactivoSalario()

valor = 0.00
dias = 0.00

If Periodos.Fields("ppl_frecuencia").Value = 2 Then	

	If Not (RetroactivosSalario.Bof And RetroactivosSalario.Eof) Then
		Do While Not RetroactivosSalario.Eof
	                                         
			dias = RetroactivosSalario.Fields("idr_dias").Value 
	        
			valor = valor + RetroactivosSalario.Fields("idr_valor").Value 
	
			RetroactivosSalario.MoveNext
		Loop
	End If
	   
	 
	If Not IsNull(Factores("RetroactivoSalario").CodTipoIngreso) And valor > 0.00 Then
		agrega_ingresos_historial Agrupadores, _
									IngresosEstaPlanilla, _
									empleados.Fields("emp_codigo").Value, _
									periodos.Fields("ppl_codigo").Value, _
									Factores("RetroactivoSalario").CodTipoIngreso, _
									valor, RubrosSalario.Fields("ese_codmon").Value, dias, "dias"
	End If

End If

RetroactivoSalario = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'AEF1DE9A-77AC-4B4A-B977-5EB3195C01CF';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('AEF1DE9A-77AC-4B4A-B977-5EB3195C01CF','DiasTrabajados','Determina la Cantidad de Dias Efectivamente trabajados por el empleado en el periodo Mensual','Function DiasTrabajados()

dias = 0  
diasiniciales = 0    
diaslimite = 0

fecha_ingreso = Empleados.Fields("emp_fecha_ingreso").Value

fecha_ini = Periodos.Fields("ppl_fecha_ini").Value 
fecha_fin = Periodos.Fields("ppl_fecha_fin").Value 

If Periodos.Fields("ppl_frecuencia").Value = 1 Then
	diaslimite = 15
Else 
	diaslimite = 30
End If

If Empleados.Fields("plz_es_temporal").Value = 0 Then 

	If fecha_ingreso >= fecha_ini And fecha_ingreso <= fecha_fin Then  
		diasiniciales = diaslimite - day(fecha_ingreso) + 1
	ElseIf fecha_ingreso > fecha_fin Then                   
		diasiniciales = 0               
	Else            
		diasiniciales = diaslimite
	End If  

Else       
	If fecha_ingreso >= fecha_ini And fecha_ingreso <= fecha_fin Then
		If fecha_ingreso > Empleados.Fields("plz_fecha_fin").Value Then                   
			diasiniciales = 0              
		ElseIf Empleados.Fields("plz_fecha_fin").Value > fecha_fin Then
			diasiniciales = diaslimite - day(fecha_ingreso) + 1    
		Else                   
			diasiniciales = datediff("d", fecha_ingreso, Empleados.Fields("plz_fecha_fin").Value) + 1 
		End If         
	ElseIf fecha_ingreso > fecha_fin Then                   
		diasiniciales = 0               
	Else              
		If Empleados.Fields("plz_fecha_fin").Value > fecha_fin Then                   
			diasiniciales = diaslimite
		Else                   
			diasiniciales = datediff("d", fecha_ini, Empleados.Fields("plz_fecha_fin").Value) + 1
		End If       
	End If  
End If          

dias = diasiniciales - _
	Factores("DiasNoTrabajados").Value - _
	Factores("DiasAmonestacion").Value - _
	Factores("DiasIncapacidad").Value - _
	Factores("DiasVacacion").Value

If dias < 0 Then       
	dias = 0  
Else       
	If dias > diaslimite Then            
		dias = diaslimite  
	End If  
End If          

DiasTrabajados = dias  

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'E4DF7856-77BE-49B8-BD75-65E5E13BD14C';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('E4DF7856-77BE-49B8-BD75-65E5E13BD14C','Vacacion','Determina el monto a pagar al empleado por los días que está de vacaciones durante la planilla Mensual','Function Vacacion()

montovac = 0.00
diasvac = 0
valor_total = 0.00
dias_total = 0

If Periodos.Fields("ppl_frecuencia").Value = 2 Then	

	If Vacaciones.RecordCount > 0 Then
		
		Vacaciones.MoveFirst
	
		If Not (Vacaciones.Bof And Vacaciones.Eof) Then 
		
			Do While Not Vacaciones.Eof   
			
			diasvac = CDbl(Vacaciones.Fields("vca_dias_calendario").Value)
			montovac = CDbl(Vacaciones.Fields("vca_valor_vacaciones").Value)
			
			dias_total = dias_total + diasvac
			valor_total = valor_total + montovac
			
			Vacaciones.MoveNext
			
			Loop
		End If
	End If
	
	If Not IsNull(Factores("Vacacion").CodTipoIngreso) And valor_total > 0 Then
	      agrega_ingresos_historial Agrupadores, _
	                                IngresosEstaPlanilla, _
	                                Empleados.Fields("emp_codigo").Value, _
	                                Periodos.Fields("ppl_codigo").Value, _
	                                Factores("Vacacion").CodTipoIngreso, _
	                                valor_total, RubrosSalario.Fields("ese_codmon").Value, dias_total, "Dias"
	
	End If
	
End If	

Vacacion= valor_total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '5938B934-34DA-4A2C-BD98-88C56B09FA8C';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('5938B934-34DA-4A2C-BD98-88C56B09FA8C','IngresoCiclico','Pagos Fijos realizados al empleado mensualmente Mensual','Function IngresoCiclico()

valor = 0.00
dias = 0

dias = Factores("DiasTrabajados").Value

If Periodos.Fields("ppl_frecuencia").Value = 2 Then	

	''''debemos garantizarnos que el cursor tiene por lo menos un registro para este empleado
	If Not (IngresosCiclicos.Bof And IngresosCiclicos.Eof)Then
		IngresosCiclicos.MoveFirst
		
		Do Until IngresosCiclicos.Eof
			
			valor = valor + IngresosCiclicos.Fields("cic_valor_cuota").Value
			
			IngresosCiclicos.Fields("cic_aplicado_planilla").Value = 1
			
			If valor > 0 Then
				agrega_ingresos_historial Agrupadores, _
											IngresosEstaPlanilla, _
											Empleados.Fields("emp_codigo").Value, _
											Periodos.Fields("ppl_codigo").Value, _
											IngresosCiclicos.Fields("igc_codtig").Value, _
											Round(IngresosCiclicos.Fields("cic_valor_cuota").Value, 0), _
											IngresosCiclicos.Fields("igc_codmon").Value, dias, "dias"
			End If
	
			IngresosCiclicos.MoveNext
		Loop
	
	End If
	
End If

IngresoCiclico = Round(valor, 0)
	
End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '0B0F5BE5-83ED-4CF4-9D77-B95E85466295';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('0B0F5BE5-83ED-4CF4-9D77-B95E85466295','BonoPactadoActual','Calcula el valor de la Bonificacion Pactada Actual Mensual','Function BonoPactadoActual()

valor = 0.00

'' Calcula Salario Actual
If Not (RubrosBonoPactado.Bof And RubrosBonoPactado.Eof) Then
	If IsNull(RubrosBonoPactado.Fields("ese_valor").Value ) Then
		valor = 0
	Else
		If RubrosBonoPactado.Fields("ese_exp_valor").Value = "Diario" Then
			valor = RubrosBonoPactado.Fields("ese_valor").Value * 30
		Else
			valor = RubrosBonoPactado.Fields("ese_valor").Value
		End If
	End If
End If
   
BonoPactadoActual = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'C032648D-F89E-4361-9722-AC9748783521';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('C032648D-F89E-4361-9722-AC9748783521','SeguroSocial','Determina el Monto a Descontar por concepto de IGSS al empleado en el periodo Mensual','Function SeguroSocial()

afecto = 0.00
cuota = 0.00
patronal = 0.00
por_cuota = 0.0000
pat_cuota = 0.0000

If Periodos.Fields("ppl_frecuencia").Value = 2 Then
	If Empleados.Fields("aplica_seguro_social").Value Then
		
		por_cuota = ParametrosAplicacion.Fields("porc_empleado_seguro_social").Value
		pat_cuota = ParametrosAplicacion.Fields("porc_patrono_seguro_social").Value
  
		afecto = Agrupadores("CRBaseCalculoCCSS").Value
      
		cuota = por_cuota / 100.00 * afecto
		
		If cuota < 0.00 Then 
			cuota = 0.00       
		End If
		
		patronal = Round(pat_cuota / 100.00 * afecto,2)
		
		If patronal < 0.00 Then  
			patronal = 0.00  
		End If                                   
		
		'' inserta el registro en la tabla de descuentos  
		If Not isnull(Factores("SeguroSocial").CodTipoDescuento) And cuota > 0.00 Then       
		 agrega_descuentos_historial Agrupadores, _
									DescuentosEstaPlanilla, _
									Empleados.Fields("emp_codigo").Value, _
									Periodos.Fields("ppl_codigo").Value, _
									Factores("SeguroSocial").CodTipoDescuento, _
									Round(cuota, 2), Round(patronal,2), afecto, Periodos.Fields("tpl_codmon").Value, _
									Factores("DiasTrabajados").Value, "Dias"
		End If
   End If

   Factores("SeguroSocialPatrono").Value = patronal 
   
End If

SeguroSocial= Round(cuota, 2)

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'FE1BE314-0831-43A0-B557-2D003F980C35';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('FE1BE314-0831-43A0-B557-2D003F980C35','SeguroSocialPatrono','Determina el Monto que deberá pagar el Patrono por Concepto de IGSS del Empleado en el periodo Mensual','Function SeguroSocialPatrono()

SeguroSocialPatrono = 0.00

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '4D268117-9C6B-46BC-9146-60CCFD686DE3';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('4D268117-9C6B-46BC-9146-60CCFD686DE3','SeguroMedico','Determina el monto de Descuento por el Seguro Medico. Mensual','Function SeguroMedico()

valor = 0.00
patronal = 0.00

If Periodos.Fields("ppl_frecuencia").Value = 2 Then

	If Not (SegurosMedicos.Bof And SegurosMedicos.Eof) Then
		patronal = SegurosMedicos.Fields("sem_cuota_patrono").Value 
		valor = SegurosMedicos.Fields("sem_cuota_empleado").Value 
	End If

	If Not IsNull(Factores("SeguroMedico").CodTipoDescuento) And valor > 0 Then       
		agrega_descuentos_historial Agrupadores, _
									DescuentosEstaPlanilla, _
									Empleados.Fields("emp_codigo").Value, _
									Periodos.Fields("ppl_codigo").Value, _
									Factores("SeguroMedico").CodTipoDescuento, _
									Round(valor, 2), patronal, 0, Periodos.Fields("tpl_codmon").Value, 0, "Dias"
	End If 

End If

SeguroMedico = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'D2091928-4505-43C4-ACA4-022CCFE1E5FB';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('D2091928-4505-43C4-ACA4-022CCFE1E5FB','DiasVacacion','Determina la cantidad de Dias a pagar al empleado por encontrarse de vacaciones Mensual','Function DiasVacacion()

dias = 0

If Not (DiasVacaciones.Bof And DiasVacaciones.Eof) Then
	Do While Not DiasVacaciones.Eof
	
		dias = dias + DiasVacaciones.Fields("vac_dias").Value 
		DiasVacaciones.MoveNext
	
	Loop

End If

DiasVacacion = dias

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '1FD70B43-6D35-4AC5-8ADB-4AFC7766C425';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('1FD70B43-6D35-4AC5-8ADB-4AFC7766C425','ComplementoBonoPactado','Complemento de Bonificacion pactada a Empleados nuevos en el periodo Anterior y sin pago efectuado Mensual','Function ComplementoBonoPactado()

'' calcula los complementos de Empleados que ingresaron en el periodo anterior siempre y cuando el anterior
'' sea el segundo periodo y que no haya tenido pago en ese periodo.
'' los dias que se toman son de la fecha de ingreso hasta el dia 30 del mes, dado que el Salario es en base
'' a 30 dias.

valor = 0.00
bono = 0.00
dias = 0.00

If Periodos.Fields("ppl_frecuencia").Value = 2 Then 

   If Not(ComplementosSalario.Bof And ComplementosSalario.Eof) Then
      
      dias = ComplementosSalario.Fields("eni_dias").Value  
      bono = Factores("BonoPactadoActual").Value

      valor = Round((bono / 30.00) * dias, 2)

   End If

   If Not IsNull(Factores("ComplementoBonoPactado").CodTipoIngreso) And vtotal > 0 Then
	  agrega_ingresos_historial Agrupadores, _
								IngresosEstaPlanilla, _
								Empleados.Fields("emp_codigo").Value, _
								Periodos.Fields("ppl_codigo").Value, _
								Factores("ComplementoBonoPactado").CodTipoIngreso, _
								valor, RubrosSalario.Fields("ese_codmon").Value, dias, "Dias"
   End If

End If

ComplementoBonoPactado = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'FAE2287C-FF22-4466-927E-AAE805E36ECA';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('FAE2287C-FF22-4466-927E-AAE805E36ECA','PrestacionEmpleado','Prestaciones del Empleado Mensual','Function PrestacionEmpleado()

valor = 0

If Periodos.Fields("ppl_frecuencia").Value = 2 Then	

	If PrestacionesEmpleado.RecordCount > 0 Then
		PrestacionesEmpleado.MoveFirst
		Do Until PrestacionesEmpleado.Eof
	
				agrega_ingresos_historial Agrupadores, _ 
							IngresosEstaPlanilla, _
							Empleados.Fields("emp_codigo").Value, _
							Periodos.Fields("ppl_codigo").Value, _
							PrestacionesEmpleado.Fields("pre_codtig").Value , _
							Round(PrestacionesEmpleado.Fields("ppp_valor").Value, 2), _
							PrestacionesEmpleado.Fields("ppp_codmon").Value, 0, "Dias"
	
				valor = valor + Round(PrestacionesEmpleado.Fields("ppp_valor").Value, 2)
	
			PrestacionesEmpleado.MoveNext
		Loop
	End If

End If

PrestacionEmpleado = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'EE32616B-288B-4D37-A1BC-9F3BB4A28C33';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('EE32616B-288B-4D37-A1BC-9F3BB4A28C33','Salario','Salario Correspondiente a esta quincena Mensual','Function Salario()

sal = 0  
diasMes = 0
dias = 0

If Periodos.Fields("ppl_frecuencia").Value = 2 Then

	diasMes = Factores("DiasDelMes").Value 

	If diasMes > 0 Then     
		sal = Factores("SalarioMensual").Value 
		dias = Factores("DiasTrabajados").Value                         

		If sal > 0 Then       
			sal = sal / DiasDelMes * dias  
		End If 
		
	End If                   


	If Not IsNull(Factores("Salario").CodTipoIngreso) And sal > 0 Then    
		agrega_ingresos_historial Agrupadores, _
									IngresosEstaPlanilla, _
									Empleados.Fields("emp_codigo").Value, _
									Periodos.Fields("ppl_codigo").Value, _
									Factores("Salario").CodTipoIngreso, _
									sal, RubrosSalario.Fields("ese_codmon").Value, dias, "Dias"
	End If

End If

Salario = sal

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '4D6352C0-4CDF-4D5C-8035-7BE6B279F6B3';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('4D6352C0-4CDF-4D5C-8035-7BE6B279F6B3','ISR','Determina el Monto a Descontar al Empleado por concepto de ISR Mensual','Function ISR()
	
If Periodos.Fields("ppl_frecuencia").Value = 2 Then	
	
	afecto = 0.00
	porc = 0.00
	excedente = 0.00
	valor = 0.00
	tasa = Factores("TasaCambio").Value
	liquido = 0.00

	liquido = Factores("TotalIngresos").Value - _
		Factores("DescuentoAnticipo").Value - _
		Factores("SeguroSocial").Value
	
	''monto afecto al impuesto sobre la renta
	afecto = Round(Agrupadores("CRBaseCalculoRenta").Value, 2)
	
	If RubrosSalario.Fields("ese_codmon").Value = "USD" Then
		afecto = afecto * tasa
	End If
	
	''recorre la tabla para obtener el excedente y porcentaje correspondiente
	If Not (TablaISRMensual.Bof And TablaISRMensual.Eof) Then
		TablaISRMensual.MoveFirst
		
		Do Until TablaISRMensual.Eof Or valor > 0.00
			''calculo del ISR
			If afecto >= TablaISRMensual.Fields("inicio").Value And afecto <= TablaISRMensual.Fields("fin").Value Then
				excedente = TablaISRMensual.Fields("excedente").Value
				porc = TablaISRMensual.Fields("porcentaje").Value
				valor = ((afecto - TablaISRMensual.Fields("inicio").Value) * porc / 100.00) + excedente
			End If
			
			TablaISRMensual.MoveNext
		Loop	
	End If
	
	''convertir de colones a dólares
	If RubrosSalario.Fields("ese_codmon").Value = "USD" Then
		valor = valor / tasa	
		afecto = afecto / tasa
	End If
	
	''resta el crédito por conyuges e hijos (si aplica)
	valor = valor - Factores("CreditoISRConyuge").Value - Factores("CreditoISRHijos").Value
	
	If valor < 0.00 Then 
		valor = 0.00
	End If
	
	If Not isnull(Factores("ISR").CodTipoDescuento) And valor > 0.00 And liquido - valor >= 0.00 Then       
		agrega_descuentos_historial Agrupadores, _
										DescuentosEstaPlanilla, _
										Empleados.Fields("emp_codigo").Value, _
										Periodos.Fields("ppl_codigo").Value, _
										Factores("ISR").CodTipoDescuento, _
										Round(valor, 2), 0.00, afecto, RubrosSalario.Fields("ese_codmon").Value, _
										Factores("DiasTrabajados").Value, "Dias"		
	End If
	
	ISR = valor	
	
End If

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '3BD0298B-4CD9-47FB-A492-E1A626A61E28';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('3BD0298B-4CD9-47FB-A492-E1A626A61E28','DescuentoCiclicoPorcentaje','Determina el Monto a Descontar al empleado por Prestamos Mensual','Function DescuentoCiclicoPorcentaje

total = 0.00
valor = 0.00
liquido = 0.00
afecto = 0.00

If Periodos.Fields("ppl_frecuencia").Value = 2 Then	

liquido = Factores("TotalIngresos").Value - _    
	Factores("DescuentoAnticipo").Value - _
	Factores("SeguroSocial").Value - _            
	Factores("ISR").Value - _  
	Factores("PensionAlimenticia").Value - _
	Factores("PensionAlimenticiaPorcentaje").Value - _
	Factores("Embargo").Value - _
	Factores("EmbargoPorcentaje").Value - _
	Factores("SeguroMedico").Value - _
	Factores("DescuentoCiclico").Value

filtro = DescuentosCiclicosPorcentaje.Filter

DescuentosCiclicosPorcentaje.Filter = filtro & " And es_pension = 0 And es_embargo = 0"

If Not (DescuentosCiclicosPorcentaje.Bof And DescuentosCiclicosPorcentaje.Eof) Then

	DescuentosCiclicosPorcentaje.MoveFirst

	Do Until DescuentosCiclicosPorcentaje.Eof
	
		If ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) > 0.00 Then

			If DescuentosCiclicosPorcentaje.Fields("dcc_codagr").Value > 0 Then
				For i = 1 To Agrupadores.count
					If Agrupadores(i).codigo = DescuentosCiclicosPorcentaje.Fields("dcc_codagr").Value Then

						valor = Round(Agrupadores(i).Value * ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) / 100.00, 2)
	
						Exit For
					End If
				Next
			Else
				valor = ccur(Factores("SalarioActual").Value) * ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) / 100.00
			End If
			
			
			If valor > 0 Then
				If (ccur(liquido) - ccur(valor)) >= 0 Then
			
					liquido = ccur(liquido) - ccur(valor)
					total = total + valor

					agrega_descuentos_historial Agrupadores, _
											DescuentosEstaPlanilla, _
											Empleados.Fields("emp_codigo").Value, _
											Periodos.Fields("ppl_codigo").Value, _
											DescuentosCiclicosPorcentaje.Fields("dcc_codtdc").Value , _
											valor, 0.00, 0.00, DescuentosCiclicosPorcentaje.Fields("dcc_codmon").Value, 0, "dias"
				End If
			End If
		End If
   
		DescuentosCiclicosPorcentaje.MoveNext
	Loop

End If

DescuentosCiclicosPorcentaje.Filter = filtro

End If

DescuentoCiclicoPorcentaje = total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '6682FB47-7243-45E7-9C35-23F4F5CCFF53';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('6682FB47-7243-45E7-9C35-23F4F5CCFF53','DiasAmonestacion','Dias Amonestacion para este periodo Mensual','Function DiasAmonestacion()

dias = 0         

If Amonestaciones.RecordCount > 0 Then              

	Amonestaciones.MoveFirst

	Do While Not Amonestaciones.Eof            

		dias = dias + Amonestaciones.Fields("amo_dias").Value 
	  
		Amonestaciones.MoveNext
		
	Loop  

End If   
		  
DiasAmonestacion = dias

End Function ','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'A17F3A43-305C-4CDB-AA15-A1790D6B483D';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('A17F3A43-305C-4CDB-AA15-A1790D6B483D','DiasIncapacidad','Determina la Cantidad de Dias a Descontar producto de una Accion de Incapacidad (suspension del IGSS Mensual','Function DiasIncapacidad()

dias = 0

If Not (DiasIncapacidades.Bof And DiasIncapacidades.Eof) Then 

	Do While Not DiasIncapacidades.Eof                                    

		dias = dias + CDbl(DiasIncapacidades.Fields("ixe_dias").Value)

		DiasIncapacidades.MoveNext       

	Loop         

End If               

DiasIncapacidad = dias

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'A8FCD9E4-04EF-4DFD-B0E5-B9BB26C32BB7';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('A8FCD9E4-04EF-4DFD-B0E5-B9BB26C32BB7','DescuentoEventual','Determina el Monto a Descontar por Otros Descuentos al Empelado Mensual','Function DescuentoEventual()

valor = 0.00  
liquido = 0.00
total = 0.00

If Periodos.Fields("ppl_frecuencia").Value = 2 Then	

liquido = Factores("TotalIngresos").Value - _    
	Factores("DescuentoAnticipo").Value - _
	Factores("SeguroSocial").Value - _            
	Factores("ISR").Value - _  
	Factores("PensionAlimenticia").Value - _
	Factores("PensionAlimenticiaPorcentaje").Value - _
	Factores("Embargo").Value - _
	Factores("EmbargoPorcentaje").Value - _
	Factores("SeguroMedico").Value - _
	Factores("DescuentoCiclico").Value - _
	Factores("DescuentoCiclicoPorcentaje").Value	

If DescuentosEventuales.RecordCount > 0 Then
	DescuentosEventuales.MoveFirst
	Do Until DescuentosEventuales.Eof
		valor = Round(DescuentosEventuales.Fields("ods_valor_a_descontar").Value, 2)
   
		If valor > liquido Then
			DescuentosEventuales.Fields("ods_aplicado_planilla").Value = 0
		Else
			liquido = liquido - valor
			total = total + valor
			DescuentosEventuales.Fields("ods_aplicado_planilla").Value = 1
			agrega_descuentos_historial Agrupadores, _
											DescuentosEstaPlanilla, _
											Empleados.Fields("emp_codigo").Value, _
											Periodos.Fields("ppl_codigo").Value, _
											DescuentosEventuales.Fields("ods_codtdc").Value, _
											valor, 0, 0, DescuentosEventuales.Fields("ods_codmon").Value, 0, "Dias"
		End If
   
		DescuentosEventuales.MoveNext
	Loop
End If
 
End If
 
DescuentoEventual= total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'BC0D5EE6-3D2E-43D8-B8C7-17152031CCC6';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('BC0D5EE6-3D2E-43D8-B8C7-17152031CCC6','RetroactivoBonoPactado','Determina el Monto por Retroactivo a pagar al empleado por Bonificacion Pactada Mensual','Function RetroactivoBonoPactado()

valor = 0.00
dias = 0.00

If Periodos.Fields("ppl_frecuencia").Value = 2 Then	

	If Not (RetroactivosBonoPactado.Bof And RetroactivosBonoPactado.Eof) Then
				   
		Do While Not RetroactivosBonoPactado.Eof
											 
			dias = RetroactivosBonoPactado.Fields("idr_dias").Value 
			
			valor = valor + RetroactivosBonoPactado.Fields("idr_valor").Value 
	
			RetroactivosBonoPactado.MoveNext
		Loop
		
	End If
	 
	If Not IsNull(Factores("RetroactivoBonoPactado").CodTipoIngreso) And valor > 0.00 Then
		agrega_ingresos_historial Agrupadores, _
								IngresosEstaPlanilla, _
								Empleados.Fields("emp_codigo").Value, _
								Periodos.Fields("ppl_codigo").Value, _
								Factores("RetroactivoBonoPactado").CodTipoIngreso, _
								valor, RubrosBonoPactado.Fields("esa_codmon").Value, dias, "dias"
	End If

End If

RetroactivoBonoPactado = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '892C71C1-98ED-45A2-B0B9-9FBCA7F0974C';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('892C71C1-98ED-45A2-B0B9-9FBCA7F0974C','Neto','Determina el Liquido a Percibir por el Empleado en el Periodo Mensual','FUNCTION Neto()

Neto = Factores("TotalIngresos").Value - _
       Factores("TotalDescuentos").Value

END FUNCTION','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '10521867-ECDF-4116-92CB-D7A2C8958A0E';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('10521867-ECDF-4116-92CB-D7A2C8958A0E','ComplementoSalario','Complemento de Salario a Empleados nuevos en el periodo Anterior y que no tienen pago efectuado Mensual','Function ComplementoSalario()

'' calcula los complementos de Empleados que ingresaron en el periodo anterior siempre y cuando el anterior
'' sea el segundo periodo y que no haya tenido pago en ese periodo.
'' los dias que se toman son de la fecha de ingreso hasta el dia 30 del mes, dado que el Salario es en base
'' a 30 dias.

valor = 0.00
sal = 0.00
dias = 0.00

If Periodos.Fields("ppl_frecuencia").Value = 2 Then 

   If Not(ComplementosSalario.Bof And ComplementosSalario.Eof) Then
      
      dias = ComplementosSalario.Fields("eni_dias").Value  
      sal = Factores("SalarioActual").Value

      valor = Round((salario / 30.00) * dias, 2)

   End If

   If Not IsNull(Factores("ComplementoSalario").CodTipoIngreso) And vtotal > 0 Then
	  agrega_ingresos_historial Agrupadores, _
								IngresosEstaPlanilla, _
								Empleados.Fields("emp_codigo").Value, _
								Periodos.Fields("ppl_codigo").Value, _
								Factores("ComplementoSalario").CodTipoIngreso, _
								valor, RubrosSalario.Fields("ese_codmon").Value, dias, "Dias"
   End If

End If

ComplementoSalario = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '2736ADB0-E80A-4994-A54C-9367C04CAA59';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('2736ADB0-E80A-4994-A54C-9367C04CAA59','BonoPactado','Valor de la Bonificacion Pactada Correspondiente al Periodo Mensual','Function BonoPactado()

bon = 0  
diasMes = 0
dias = 0

If Periodos.Fields("ppl_frecuencia").Value = 2 Then 

	diasMes = Factores("DiasDelMes").Value 

	If DiasDelMes > 0 Then     
		bon = Factores("BonoPactadoMensual").Value 
		
		dias = Factores("DiasTrabajados").Value + _
			   Factores("DiasIncapacidad").Value                    

		If bon > 0 Then       
			bon = bon / DiasDelMes * dias  
		End If 
	End If                   

	If Not IsNull(Factores("BonoPactado").CodTipoIngreso) And bon > 0 Then    
		agrega_ingresos_historial Agrupadores, _
									IngresosEstaPlanilla, _
									Empleados.Fields("emp_codigo").Value, _
									Periodos.Fields("ppl_codigo").Value, _
									Factores("BonoPactado").CodTipoIngreso, _
									bon, RubrosBonoPactado.Fields("ese_codmon").Value, dias, "Dias"
	End If

End If

BonoPactado = bon 

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'C65A9D17-52B6-4764-9912-E48C24C9A60C';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('C65A9D17-52B6-4764-9912-E48C24C9A60C','BonoPactadoMensual','Bono Pactado Mensual ajustado por si hubo incrementos o si el ingreso fue en el mes Mensual','Function BonoPactadoMensual()

bonmensual = 0.00
bonanterior = 0.00 

diasanterior = 0
diasactual = 0
tasa = 0.00

If Not (TasasCambio.Bof And TasasCambio.Eof) Then
	tasa = TasasCambio.Fields("tca_tasa").Value
End If

'' --- Salario Mensual Actual
bonmensual = Round(Factores("BonoPactadoActual").Value,2)

'' --- Fecha inicial y final de la planilla
fini = Periodos.Fields("ppl_fecha_ini").Value
ffin = Periodos.Fields("ppl_fecha_fin").Value

'' --- Calcula el Salario anterior si tuvo aumentos
If Not (RubrosBonoPactadoHistorial.Bof And RubrosBonoPactadoHistorial.Eof) Then
	RubrosBonoPactadoHistorial.MoveFirst
	
	bonmensual = 0.00
	
	Do Until RubrosBonoPactadoHistorial.Eof
		bonanterior = RubrosBonoPactadoHistorial.Fields("ese_valor").Value
		
		fechaini = RubrosBonoPactadoHistorial.Fields("ese_fecha_inicio").Value
		fechafin = RubrosBonoPactadoHistorial.Fields("ese_fecha_fin").Value
		
		If fechaini < fini Then
			fechaini = fini
		End If
		
		If IsNull(fechafin) Or fechafin > ffin Then
			fechafin = ffin
		End If
		
		If (Day(RubrosBonoPactadoHistorial.Fields("ese_fecha_inicio").Value) > 30) Or (Month(RubrosBonoPactadoHistorial.Fields("ese_fecha_inicio").Value) = 2 And Day(RubrosBonoPactadoHistorial.Fields("ese_fecha_inicio").Value) >= 28) Then			
				diasanterior = 30 - Day(fechaini)
			Else
				diasanterior = DateDiff("d", fechaini, fechafin) + 1
		End If
		
		If RubrosBonoPactado.Fields("ese_codmon").Value = "USD" And  RubrosBonoPactadoHistorial.Fields("ese_codmon").Value = "CRC" Then
			bonanterior = bonanterior / tasa
		End If
		
		If RubrosBonoPactado.Fields("ese_codmon").Value = "CRC" And  RubrosBonoPactadoHistorial.Fields("ese_codmon").Value = "USD" Then
			bonanterior = bonanterior * tasa
		End If
		
		bonanterior = bonanterior / 30 * diasanterior
		
		bonmensual = bonmensual + bonanterior
		
		RubrosBonoPactadoHistorial.MoveNext
	Loop
End If   

BonoPactadoMensual = Round(bonmensual, 2)

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'BA92629E-E0FD-439C-BAA9-74415954B58F';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('BA92629E-E0FD-439C-BAA9-74415954B58F','SalarioMensual','Sueldo Mensual ajustado por si hubo incrementos o si el ingreso fue en el mes Mensual','Function SalarioMensual()

salmensual = 0.00
salanterior = 0.00 

diasanterior = 0
diasactual = 0
tasa = 0.00

If Not (TasasCambio.Bof And TasasCambio.Eof) Then
	tasa = TasasCambio.Fields("tca_tasa").Value
End If

'' --- Salario Mensual Actual
salmensual = Round(Factores("SalarioActual").Value,2)

'' --- Fecha inicial y final de la planilla
fini = Periodos.Fields("ppl_fecha_ini").Value
ffin = Periodos.Fields("ppl_fecha_fin").Value

'' --- Calcula el Salario anterior si tuvo aumentos
If Not (RubrosSalarioHistorial.Bof And RubrosSalarioHistorial.Eof) Then
	RubrosSalarioHistorial.MoveFirst
	
	salmensual = 0.00
	
	Do Until RubrosSalarioHistorial.Eof
		salanterior = RubrosSalarioHistorial.Fields("ese_valor").Value
		
		fechaini = RubrosSalarioHistorial.Fields("ese_fecha_inicio").Value
		fechafin = RubrosSalarioHistorial.Fields("ese_fecha_fin").Value
		
		If fechaini < fini Then
			fechaini = fini
		End If
		
		If IsNull(fechafin) Or fechafin > ffin Then
			fechafin = ffin
		End If
		
		If (Day(RubrosSalarioHistorial.Fields("ese_fecha_inicio").Value) > 30) Or (Month(RubrosSalarioHistorial.Fields("ese_fecha_inicio").Value) = 2 And Day(RubrosSalarioHistorial.Fields("ese_fecha_inicio").Value) >= 28) Then			
				diasanterior = 30 - Day(fechaini)
			Else
				diasanterior = DateDiff("d", fechaini, fechafin) + 1
		End If
		
		If RubrosSalario.Fields("ese_codmon").Value = "USD" And  RubrosSalarioHistorial.Fields("ese_codmon").Value = "CRC" Then
			salanterior = salanterior / tasa
		End If
		
		If RubrosSalario.Fields("ese_codmon").Value = "CRC" And  RubrosSalarioHistorial.Fields("ese_codmon").Value = "USD" Then
			salanterior = salanterior * tasa
		End If
		
		salanterior = salanterior / 30 * diasanterior
		
		salmensual = salmensual + salanterior
		
		RubrosSalarioHistorial.MoveNext
	Loop
End If   

SalarioMensual = Round(salmensual, 2)

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '8B1822AA-600A-4BF7-BA79-2C727613F8C5';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('8B1822AA-600A-4BF7-BA79-2C727613F8C5','PrestacionIncapacidad','Complemento por suspension del seguro social Mensual','Function PrestacionIncapacidad()

valor_incap = 0.00
valor_total = 0.00
dias_incap = 0.00
dias_total = 0.00

If Periodos.Fields("ppl_frecuencia").Value = 2 Then 
   
   If Incapacidades.RecordCount > 0 Then
     
      Incapacidades.MoveFirst

      If Not (Incapacidades.Bof And Incapacidades.Eof) Then 

         Do While Not Incapacidades.Eof   

            dias_incap = CDbl(Incapacidades.Fields("pie_dias").Value)
            valor_incap = CDbl(Incapacidades.Fields("pie_valor_a_pagar").Value)

            dias_total = dias_total + dias_incap
            valor_total = valor_total + valor_incap

            Incapacidades.MoveNext

         Loop

         If Not IsNull(Factores("PrestacionIncapacidad").CodTipoIngreso) And valor_total > 0 Then
            agrega_ingresos_historial Agrupadores, _
                                IngresosEstaPlanilla, _
                                Empleados.Fields("emp_codigo").Value, _
                                Periodos.Fields("ppl_codigo").Value, _
                                Factores("PrestacionIncapacidad").CodTipoIngreso, _
                                valor_total, RubrosSalario.Fields("ese_codmon").Value, dias_total, "Dias"

         End If

      End If

   End If

End If

PrestacionIncapacidad = valor_total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '24B03A26-2304-404D-8AB0-E05B66944507';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('24B03A26-2304-404D-8AB0-E05B66944507','DiasDelMes','Dias del Mes sera 30 o los dias desde la fecha de ingreso en el mes hasta 30 Mensual','Function DiasDelMes()

dias = 0.00

If Empleados.Fields("emp_fecha_ingreso").Value > Periodos.Fields("ppl_fecha_ini").Value And _
	Empleados.Fields("emp_fecha_ingreso").Value <= Periodos.Fields("ppl_fecha_fin").Value Then
	dias = 30.00 - day(Empleados.Fields("emp_fecha_ingreso").Value) + 1
Else
	dias = 30.00
End If
   
DiasDelMes = dias

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '771272D6-ABE4-46D1-8904-FD92B09C9709';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('771272D6-ABE4-46D1-8904-FD92B09C9709','AntipoQuincenal','Valor del Anticipo a pagar en la quincena','Function AntipoQuincenal()

diasmes = 0
diasquincena = 0
anticipo = 0.00
salariov = 0  
bonopactadov = 0
dias = 0
porcentaje = 0

''--- toma dias del mes que contiene 30 o los dias desde la fecha de ingreso
''--- porque el Salario, BonoPactado y BonoLey solo corresponden a ese numero de dias
''--- a ese numero le resta 15 que corresponde a la segunda quincena

diasmes = Factores("DiasDelMes").Value 
diasquincena = diasmes - 15

If Periodos.Fields("ppl_frecuencia").Value = 1 And diasquincena > 0 Then

	If Empleados.Fields("aplica_anticipo").Value Then
	   porcentaje = Empleados.Fields("emp_porcentaje_anticipo").Value 
	Else 
		porcentaje = ParametrosAplicacion.Fields("porcentaje_anticipo").Value
	End If
	
	salariov     = Factores("SalarioActual").Value * porcentaje / 100.00
	bonopactadov = Factores("BonoPactadoActual").Value * porcentaje / 100.00

	dias = Factores("DiasTrabajados").Value      

	If salariov > 0 Then       
	   salariov = salariov / diasquincena * dias  
	End If 
	
	If bonopactadov > 0 Then       
	   bonopactadov = bonopactadov / diasquincena * dias
	End If 

	anticipo = salariov + bonopactadov

	If Not IsNull(Factores("AntipoQuincenal").CodTipoIngreso) And anticipo > 0 Then    
		agrega_ingresos_historial Agrupadores, _
									IngresosEstaPlanilla, _
									Empleados.Fields("emp_codigo").Value, _
									Periodos.Fields("ppl_codigo").Value, _
									Factores("AntipoQuincenal").CodTipoIngreso, _
									anticipo, Periodos.Fields("tpl_codmon").Value, dias, "Dias"

	End If

End If

AntipoQuincenal = anticipo 

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '9AF92F8E-9E38-439E-AE48-C798574FE27F';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('9AF92F8E-9E38-439E-AE48-C798574FE27F','DescuentoAnticipo','Descuento por anticipo de Salario','Function DescuentoAnticipo()

valor = 0.00
filtroactual = ""

If Periodos.Fields("ppl_frecuencia").Value = 2 Then
	If Not(PeriodosAnteriores.Bof And PeriodosAnteriores.Eof) Then
		If Not ((IngresosPlanillaAnterior.Bof) And (IngresosPlanillaAnterior.Eof)) Then
		
			filtroactual = IngresosPlanillaAnterior.Filter          

			IngresosPlanillaAnterior.Filter = filtroactual & " And inn_codppl = " & PeriodosAnteriores.Fields("ppl_codigo").Value _
												& " And inn_codtig = " & Factores("AntipoQuincenal").codtipoingreso

			Do While Not IngresosPlanillaAnterior.Eof                                    
				valor = valor + IngresosPlanillaAnterior.Fields("inn_valor").Value                        
				IngresosPlanillaAnterior.MoveNext       
			Loop  

			IngresosPlanillaAnterior.Filter = filtroactual           
		End If               
	End If
  
	If Not isnull( Factores("DescuentoAnticipo").CodTipoDescuento) And valor > 0 Then       

		agrega_descuentos_historial Agrupadores, _
									DescuentosEstaPlanilla, _
									Empleados.Fields("emp_codigo").Value, _
									Periodos.Fields("ppl_codigo").Value, _
									Factores("DescuentoAnticipo").CodTipoDescuento, _
									Round(valor, 2), 0, 0, Periodos.Fields("tpl_codmon").Value, 0, "Dias"

	End If
End If

DescuentoAnticipo  = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'a1f666e2-3cb0-4df9-85d4-2d6c40cbdcc6';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('a1f666e2-3cb0-4df9-85d4-2d6c40cbdcc6','Sustitucion','Monto de la sustitucions o coberturas','Function Sustitucion()

monto = 0.00
dias = 0
valor_total = 0.00
dias_total = 0

If Periodos.Fields("ppl_frecuencia").Value = 2 Then	

	If Sustituciones.RecordCount > 0 Then
		Sustituciones.MoveFirst
	
		If Not (Sustituciones.Bof And Sustituciones.Eof) Then 
		
		Do While Not Sustituciones.Eof   
		
		dias = CDbl(Sustituciones.Fields("ste_dias").Value)
		monto = CDbl(Sustituciones.Fields("ste_valor").Value)
		
		dias_total = dias_total + dias
		valor_total = valor_total + monto
		
		Sustituciones.MoveNext
		
		Loop
		
		End If
	End If	
	
	If Not isnull(Factores("Sustitucion").CodTipoIngreso) And valor_total > 0 Then
	      agrega_ingresos_historial Agrupadores, _
	                                IngresosEstaPlanilla, _
	                                Empleados.Fields("emp_codigo").Value, _
	                                Periodos.Fields("ppl_codigo").Value, _
	                                Factores("Sustitucion").CodTipoIngreso, _
	                                valor_total, RubrosSalario.Fields("ese_codmon").Value, dias_total, "Dias"
	
	End If

End If

Sustitucion = valor_total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '179c928d-42ce-4807-8e9d-187136471953';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('179c928d-42ce-4807-8e9d-187136471953','CreditoISRConyuge','El monto que se descuenta al ISR del empleado si tiene conyugüe','Function CreditoISRConyuge

	valor = 0.00
	tasa = Factores("TasaCambio").Value
	
	If Empleados.Fields("aplica_isr_conyugue").Value Then
		valor = ParametrosAplicacion.Fields("isr_valor_conyugue").Value
		
		If RubrosSalario.Fields("ese_codmon").Value = "USD" Then
			tasa = TasaCambio.Fields("tca_tasa").Value
			
			valor = valor / tasa
		End If
	End If
	
	CreditoISRConyuge = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'ec1133a0-5886-4afc-a67c-4bdc2baae0fa';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('ec1133a0-5886-4afc-a67c-4bdc2baae0fa','TasaCambio','Tasa cambio de colones a dólares a utilizar en la planilla','Function TasaCambio()

valor = 0.00

If Not (TasasCambio.Bof And TasasCambio.Eof) Then
	valor = TasasCambio.Fields("tca_tasa").Value
End If

TasaCambio = valor

End Function','double','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'b83b0ff0-b3a6-45eb-a7c0-907f411ee4c2';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('b83b0ff0-b3a6-45eb-a7c0-907f411ee4c2','CreditoISRHijos','El monto que se descuenta al ISR del empleado por el número de hijos que tiene','Function CreditoISRHijos

valor = 0.00
tasa = Factores("TasaCambio").Value

numHijos = Empleados.Fields("emp_numero_hijos").Value
valor = ParametrosAplicacion.Fields("isr_valor_hijos").Value * numHijos
	
If RubrosSalario.Fields("ese_codmon").Value = "USD" Then
	tasa = TasaCambio.Fields("tca_tasa").Value
	valor = valor / tasa
End If

CreditoISRHijos = valor

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '91e30827-b796-4422-8a2d-37c6ff9e8e8e';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('91e30827-b796-4422-8a2d-37c6ff9e8e8e','PensionAlimenticia','Monto de descuentos cíclicos para la pensión alimenticia','Function PensionAlimenticia

total = 0.00
valor = 0.00
liquido = 0.00
embargoMaximo = 0.00
porcMaxPension = ParametrosAplicacion.Fields("pal_porcentaje_maximo").Value

If Periodos.Fields("ppl_frecuencia").Value = 2 Then	

	liquido = Factores("TotalIngresos").Value - _    
		Factores("DescuentoAnticipo").Value - _
		Factores("SeguroSocial").Value - _            
		Factores("ISR").Value		  
	
	embargoMaximo = Factores("TotalIngresos").Value * porcMaxPension / 100.00
	
	filtro = DescuentosCiclicos.Filter
	
	DescuentosCiclicos.Filter = filtro & " And es_pension = 1"
	
	If Not (DescuentosCiclicos.Bof And DescuentosCiclicos.Eof) Then
		DescuentosCiclicos.MoveFirst
		Do Until DescuentosCiclicos.Eof
		
			valor = Round(DescuentosCiclicos.Fields("cdc_valor_cobrado").Value, 2)
		
			If liquido - valor >= 0 And embargoMaximo - valor >= 0 Then
				liquido = liquido - valor
				embargoMaximo = embargoMaximo - valor
				total = total + valor
				DescuentosCiclicos.Fields("cdc_fecha_descuento").Value = Periodos.Fields("ppl_fecha_pago").Value
				DescuentosCiclicos.Fields("cdc_aplicado_planilla").Value = 1
		
				agrega_descuentos_historial Agrupadores, _
												DescuentosEstaPlanilla, _
												Empleados.Fields("emp_codigo").Value, _
												Periodos.Fields("ppl_codigo").Value, _
												DescuentosCiclicos.Fields("dcc_codtdc").Value, _
												valor, 0, 0, DescuentosCiclicos.Fields("dcc_codmon").Value, 0, "dias"
			Else
				DescuentosCiclicos.Fields("cdc_aplicado_planilla").Value = 0
			End If
		    
			DescuentosCiclicos.MoveNext
		Loop 	
	End If
	
	DescuentosCiclicos.Filter = filtro
	
End If	

PensionAlimenticia = total
	
End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '7140a761-88f6-4e84-9e86-66559cef18b6';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('7140a761-88f6-4e84-9e86-66559cef18b6','PensionAlimenticiaPorcentaje','Monto de descuentos cíclicos por porcentaje para la pensión alimenticia','Function PensionAlimenticiaPorcentaje

total = 0.00
valor = 0.00
liquido = 0.00
afecto = 0.00
embargoMaximo = 0.00
porcMaxPension = ParametrosAplicacion.Fields("pal_porcentaje_maximo").Value

If Periodos.Fields("ppl_frecuencia").Value = 2 Then	

	liquido = Round(Factores("TotalIngresos").Value - _		
		Factores("DescuentoAnticipo").Value - _
		Factores("SeguroSocial").Value - _
		Factores("ISR").Value - _
		Factores("PensionAlimenticia").Value, 2)
	
	embargoMaximo = (Factores("TotalIngresos").Value * porcMaxPension / 100.00) - Factores("PensionAlimenticia").Value
	
	filtro = DescuentosCiclicosPorcentaje.Filter
	
	DescuentosCiclicosPorcentaje.Filter = filtro & " And es_pension = 1"
	
	If Not (DescuentosCiclicosPorcentaje.Bof And DescuentosCiclicosPorcentaje.Eof) Then
	
		DescuentosCiclicosPorcentaje.MoveFirst
		
		Do Until DescuentosCiclicosPorcentaje.Eof
			If DescuentosCiclicosPorcentaje.Fields("dcc_frecuencia_periodo_pla").Value = Periodos.Fields("ppl_frecuencia").Value Or _
				DescuentosCiclicosPorcentaje.Fields("dcc_frecuencia_periodo_pla").Value = "0" Then
				
				If ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) > 0.00 Then
		
					If DescuentosCiclicosPorcentaje.Fields("dcc_codagr").Value > 0 Then
						For i = 1 To Agrupadores.count
							If Agrupadores(i).codigo = DescuentosCiclicosPorcentaje.Fields("dcc_codagr").Value Then
		
								valor = Round(Agrupadores(i).Value * ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) / 100.00, 2)
			
								Exit For
							End If
						Next
					Else
						valor = ccur(Factores("SalarioActual").Value) * ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) / 100.00
					End If
					
					
					If valor > 0.00 And liquido - valor >= 0.00 And embargoMaximo - valor >= 0.00  Then
							liquido = ccur(liquido) - ccur(valor)
							embargoMaximo = embargoMaximo - valor
							total = total + valor
		
							agrega_descuentos_historial Agrupadores, _
													DescuentosEstaPlanilla, _
													Empleados.Fields("emp_codigo").Value, _
													Periodos.Fields("ppl_codigo").Value, _
													DescuentosCiclicosPorcentaje.Fields("dcc_codtdc").Value , _
													valor, 0.00, 0.00, DescuentosCiclicosPorcentaje.Fields("dcc_codmon").Value, 0, "dias"
					End If
				End If
			End If
		   
			DescuentosCiclicosPorcentaje.MoveNext
		Loop		
	End If
	
	DescuentosCiclicosPorcentaje.Filter = filtro

End If

PensionAlimenticiaPorcentaje = total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '8885f9d9-7e3f-4f72-ab32-90eb99a79d52';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('8885f9d9-7e3f-4f72-ab32-90eb99a79d52','Embargo','Monto de descuentos cíclicos para el embargo','Function Embargo

total = 0.00
valor = 0.00
liquido = 0.00
salarioEmbargable = 0.00
salarioInembargable = 0.00
embargoMaximo = 0.00
porcMenor = 0
porcMayor = 0
numSalMinimos = 0

If Periodos.Fields("ppl_frecuencia").Value = 2 Then	

	liquido = Factores("TotalIngresos").Value - _    
		Factores("DescuentoAnticipo").Value - _
		Factores("SeguroSocial").Value - _            
		Factores("ISR").Value - _  
		Factores("PensionAlimenticia").Value - _
		Factores("PensionAlimenticiaPorcentaje").Value
			  
	salarioInembargable = ParametrosAplicacion.Fields("emb_salario_inembargable").Value
	porcMenor = ParametrosAplicacion.Fields("emb_porcentaje_menores").Value
	porcMayor = ParametrosAplicacion.Fields("emb_porcentaje_mayores").Value
	numSalMinimos = ParametrosAplicacion.Fields("emb_num_sal_minimos").Value
	
	If RubrosSalario.Fields("ese_codmon").Value = "USD" Then
		salarioInembargable = salarioInembargable / TasaCambio.Fields("tca_tasa").Value
	End If
	
	salarioEmbargable = Factores("TotalIngresos").Value - _    
		Factores("SeguroSocial").Value - _            
		Factores("ISR").Value - _  
		Factores("PensionAlimenticia").Value - _
		Factores("PensionAlimenticiaPorcentaje").Value - _
		salarioInembargable	
	
	If Factores("TotalIngresos").Value > 0 And Factores("TotalIngresos").Value < salarioInembargable * numSalMinimos Then
		embargoMaximo = round(salarioEmbargable * porcMenor / 100.00, 2)
	Else
		embargoMaximo = round(salarioEmbargable * porcMayor / 100.00, 2)
	End If      
	
	filtro =  DescuentosCiclicos.Filter
	
	DescuentosCiclicos.Filter = filtro & " And es_embargo = 1"
	
	If Not (DescuentosCiclicos.Bof And DescuentosCiclicos.Eof) Then
	
		DescuentosCiclicos.MoveFirst
		
		Do Until DescuentosCiclicos.Eof
		
			valor = Round(DescuentosCiclicos.Fields("cdc_valor_cobrado").Value, 2)
		
			If liquido - valor >= 0 And embargoMaximo - valor >= 0 Then
				liquido = liquido - valor
				embargoMaximo = embargoMaximo - valor
				total = total + valor
				DescuentosCiclicos.Fields("cdc_fecha_descuento").Value = Periodos.Fields("ppl_fecha_pago").Value
				DescuentosCiclicos.Fields("cdc_aplicado_planilla").Value = 1
		
				agrega_descuentos_historial Agrupadores, _
												DescuentosEstaPlanilla, _
												Empleados.Fields("emp_codigo").Value, _
												Periodos.Fields("ppl_codigo").Value, _
												DescuentosCiclicos.Fields("dcc_codtdc").Value, _
												valor, 0, 0, DescuentosCiclicos.Fields("dcc_codmon").Value, 0, "dias"
			Else
				DescuentosCiclicos.Fields("cdc_aplicado_planilla").Value = 0
			End If
			
			DescuentosCiclicos.MoveNext
		Loop	
	End If
	
	DescuentosCiclicos.Filter = filtro
	
End If	

Embargo  = total
	
End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = 'aaac5fa3-9cc3-4b56-ab9b-a9849d402898';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('aaac5fa3-9cc3-4b56-ab9b-a9849d402898','EmbargoPorcentaje','Monto de descuentos cíclcios por porcentaje para embargos','Function EmbargoPorcentaje 

total = 0.00
valor = 0.00
liquido = 0.00
salarioEmbargable = 0.00
salarioInembargable = 0.00
embargoMaximo = 0.00
porcMenor = 0
porcMayor = 0
numSalMinimos = 0

If Periodos.Fields("ppl_frecuencia").Value = 2 Then	

	liquido = Factores("TotalIngresos").Value - _    
		Factores("DescuentoAnticipo").Value - _
		Factores("SeguroSocial").Value - _            
		Factores("ISR").Value - _  
		Factores("PensionAlimenticia").Value - _
		Factores("PensionAlimenticiaPorcentaje").Value - _
		Factores("Embargo").Value
		
	salarioInembargable = ParametrosAplicacion.Fields("emb_salario_inembargable").Value
	porcMenor = ParametrosAplicacion.Fields("emb_porcentaje_menores").Value
	porcMayor = ParametrosAplicacion.Fields("emb_porcentaje_mayores").Value
	numSalMinimos = ParametrosAplicacion.Fields("emb_num_sal_minimos").Value
	
	If RubrosSalario.Fields("ese_codmon").Value = "USD" Then
		salarioInembargable = salarioInembargable / TasaCambio.Fields("tca_tasa").Value
	End If
	
	salarioEmbargable = Factores("TotalIngresos").Value - _    
		Factores("SeguroSocial").Value - _            
		Factores("ISR").Value - _  
		Factores("PensionAlimenticia").Value - _
		Factores("PensionAlimenticiaPorcentaje").Value - _
		Factores("Embargo").Value - _
		salarioInembargable
		
	If Factores("TotalIngresos").Value > 0 And Factores("TotalIngresos").Value < salarioInembargable * numSalMinimos Then
		embargoMaximo = salarioEmbargable * porcMenor / 100.00
	Else
		embargoMaximo = salarioEmbargable * porcMayor / 100.00
	End If      
	
	embargoMaximo = embargoMaximo - Factores("Embargo").Value
	
	filtro =  DescuentosCiclicosPorcentaje.Filter
	
	DescuentosCiclicosPorcentaje.Filter = filtro & " And es_embargo = 1"
	
	If Not (DescuentosCiclicosPorcentaje.Bof And DescuentosCiclicosPorcentaje.Eof) Then
	
		DescuentosCiclicosPorcentaje.MoveFirst
	
		Do Until DescuentosCiclicosPorcentaje.Eof
		
			If DescuentosCiclicosPorcentaje.Fields("dcc_frecuencia_periodo_pla").Value = Periodos.Fields("ppl_frecuencia").Value Or _
				DescuentosCiclicosPorcentaje.Fields("dcc_frecuencia_periodo_pla").Value = "0" Then
		
				If ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) > 0.00 Then
		
					If DescuentosCiclicosPorcentaje.Fields("dcc_codagr").Value > 0 Then
						For i = 1 To Agrupadores.count
							If Agrupadores(i).codigo = DescuentosCiclicosPorcentaje.Fields("dcc_codagr").Value Then
		
								valor = Round(Agrupadores(i).Value * ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) / 100.00, 2)
			
								Exit For
							End If
						Next
					Else
						valor = ccur(Factores("SalarioActual").Value) * ccur(DescuentosCiclicosPorcentaje.Fields("dcc_porcentaje").Value) / 100.00
					End If
					
					
					If valor > 0.00 And liquido - valor >= 0 And embargoMaximo = valor >= 0 Then
					
						liquido = liquido - valor
						embargoMaximo = embargoMaximo - valor
						total = total + valor
	
						agrega_descuentos_historial Agrupadores, _
												DescuentosEstaPlanilla, _
												Empleados.Fields("emp_codigo").Value, _
												Periodos.Fields("ppl_codigo").Value, _
												DescuentosCiclicosPorcentaje.Fields("dcc_codtdc").Value , _
												valor, 0.00, 0.00, DescuentosCiclicosPorcentaje.Fields("dcc_codmon").Value, 0, "dias"
												
					End If
				End If
			End If
		   
			DescuentosCiclicosPorcentaje.MoveNext
		Loop		
	End If 	
	
	DescuentosCiclicosPorcentaje.Filter = filtro
	
End If	

EmbargoPorcentaje  = total

End Function','money','cr',0);

/* Script generated by Evolution - FormulaEditor. 14/08/2014 11:23 a.m. */

delete from sal.fac_factores where fac_codigo = '6c75d732-8e35-4906-a9d7-ee750473ba29';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codfld,fac_codpai,fac_size) values ('6c75d732-8e35-4906-a9d7-ee750473ba29','TotalDescuentos','Total de descuentos del empleado','Function TotalDescuentos

TotalDescuentos = Factores("DescuentoAnticipo").Value + _
	Factores("SeguroSocial").Value + _
	Factores("ISR").Value + _
	Factores("PensionAlimenticia").Value + _
	Factores("PensionAlimenticiaPorcentaje").Value + _
	Factores("Embargo").Value + _
	Factores("EmbargoPorcentaje").Value + _
	Factores("SeguroMedico").Value + _
	Factores("DescuentoCiclico").Value + _
	Factores("DescuentoCiclicoPorcentaje").Value + _
	Factores("DescuentoEventual").Value

End Function','double','cr',0);

COMMIT