/* Script generated by Evolution - FormulaEditor. 20/01/2014 03:42 p.m. */

begin transaction

delete from sal.fac_factores where fac_codigo = '4c00809e-a9ba-4935-8b67-bc0795f30dae';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codpai,fac_size) values ('4c00809e-a9ba-4935-8b67-bc0795f30dae','agrega_descuentos_historial','Agrega los descuentos generados a la tabla temporal con el histórico','Sub agrega_descuentos_historial(ByRef Agrupadores, _
                                ByRef dss_descuentos, _
                                ByVal codEMP, _
                                ByVal codPPL, _
                                ByVal codTDC, _
                                ByVal Valor, _
                                ByVal ValorPatronal, _
                                Byval IngresoAfecto, _
                                ByVal codMON, _
                                ByVal Tiempo, _
                                ByVal UnidadTiempo)
    dss_descuentos.AddNew
    dss_descuentos.Fields("dss_codppl").Value = codPPL
    dss_descuentos.Fields("dss_codemp").Value = codEMP
    dss_descuentos.Fields("dss_codtdc").Value = codTDC
    dss_descuentos.Fields("dss_valor").Value = Valor
    dss_descuentos.Fields("dss_valor_patronal").Value = ValorPatronal
    dss_descuentos.Fields("dss_ingreso_afecto").Value = IngresoAfecto
    dss_descuentos.Fields("dss_codmon").Value = codMON
    dss_descuentos.Fields("dss_tiempo").Value = Tiempo
    dss_descuentos.Fields("dss_unidad_tiempo").Value = UnidadTiempo

	Agrupadores.SumaRubro "D", codTDC, Valor
End Sub','gt',0);

commit transaction;

/* Script generated by Evolution - FormulaEditor. 20/01/2014 03:42 p.m. */

begin transaction

delete from sal.fac_factores where fac_codigo = 'e7aa5fdd-e814-4900-976a-b48d8d0599fd';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codpai,fac_size) values ('e7aa5fdd-e814-4900-976a-b48d8d0599fd','agrega_ingresos_historial','Agrega los ingresos generados a la tabla temporal con el histórico','Sub agrega_ingresos_historial(ByRef Agrupadores, _
								 ByRef inn_ingresos, _
                              ByVal codEMP, _
                              ByVal codPPL, _
                              ByVal codTIG, _
                              ByVal Valor, _
                              ByVal codMON, _
                              ByVal Tiempo, _
                              ByVal UnidadTiempo)
	inn_ingresos.AddNew
	inn_ingresos.Fields("inn_codppl").Value = codPPL
	inn_ingresos.Fields("inn_codemp").Value = codEMP
	inn_ingresos.Fields("inn_codtig").Value = codTIG
	inn_ingresos.Fields("inn_valor").Value = Valor
	inn_ingresos.Fields("inn_codmon").Value = codMON
	inn_ingresos.Fields("inn_tiempo").Value = Tiempo
	inn_ingresos.Fields("inn_unidad_tiempo").Value = UnidadTiempo
	
	Agrupadores.SumaRubro "I", codTIG, Valor
End Sub','gt',0);

commit transaction;

/* Script generated by Evolution - FormulaEditor. 20/01/2014 03:42 p.m. */

begin transaction

delete from sal.fac_factores where fac_codigo = 'd5c42712-53e3-42d6-9634-5b0fc67cda95';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codpai,fac_size) values ('d5c42712-53e3-42d6-9634-5b0fc67cda95','agrega_reservas_historial','Agrega las reservas generadas a la tabla temporal con el histórico','Sub agrega_reservas_historial(ByRef Agrupadores, _
								 ByRef res_reservas, _
                              ByVal codEMP, _
                              ByVal codPPL, _
                              ByVal codTRS, _
                              ByVal Valor, _
                              ByVal codMON, _
                              ByVal Tiempo, _
                              ByVal UnidadTiempo)
	res_reservas.AddNew
	res_reservas.Fields("res_codppl").Value = codPPL
	res_reservas.Fields("res_codemp").Value = codEMP
	res_reservas.Fields("res_codtrs").Value = codTRS
	res_reservas.Fields("res_valor").Value = Valor
	res_reservas.Fields("res_codmon").Value = codMON
	res_reservas.Fields("res_tiempo").Value = Tiempo
	res_reservas.Fields("res_unidad_tiempo").Value = UnidadTiempo
End Sub','gt',0);

commit transaction;

/* Script generated by Evolution - FormulaEditor. 20/01/2014 03:43 p.m. */

begin transaction

delete from sal.fac_factores where fac_codigo = '8bd48491-cf15-4ab7-b036-9fe6c2f73e0a';

insert into sal.fac_factores (fac_codigo,fac_id,fac_descripcion,fac_vbscript,fac_codpai,fac_size) values ('8bd48491-cf15-4ab7-b036-9fe6c2f73e0a','writeLog','Escribe mensajes enviados desde la formulación en un archivo físico','Sub writeLog(ByVal msg)
    Dim fs, f
    Set fs = CreateObject("Scripting.FileSystemObject")
    Set f = fs.OpenTextFile("C:\Program Files (x86)\ASEINFO\logfile.txt", 8, True)
    f.Write msg
    f.Write Chr(13)
    f.Close
End Sub','gt',0);

commit transaction;
