/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

declare @codfcu_principal int

select @codfcu_principal = fcu_codigo
from sal.fcu_formulacion_cursores
where fcu_codpai = 'gt'
	and fcu_nombre = 'Empleados'

update sal.ftp_formulacion_tipos_planilla
SET ftp_codfcu_loop = NULL
where ftp_codfcu_loop = @codfcu_principal

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'Empleados';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codcia,fcu_field_codtpl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','Empleados','Empleados','SELECT 0 EMP_CODIGO,
     '''' EMP_ESTADO,
     GETDATE() EMP_FECHA_INGRESO,
     GETDATE() EMP_FECHA_RETIRO,
     0 EMP_CODJOR,
     0 EMP_CODTPL,
     0 EMP_CODPLZ,
     GETDATE() EMP_CONTRATO_INI, 
     GETDATE() EMP_CONTRATO_FIN,
     0 plz_indefinida, 
     GETDATE() plz_fecha_ini,
     GETDATE() plz_fecha_fin,
     GETDATE()  emp_fecha_ultimo_incremento,
     0 dpl_seguro_social,
     0 dpl_renta,
     0 dpl_anticipo_activo,
     0 dpl_descuenta_ornato,
     0.00 dpl_porcentaje_anticipo','SELECT EMP_CODIGO,
     EMP_ESTADO,
     EMP_FECHA_INGRESO,
     EMP_FECHA_RETIRO,
     EMP_CODJOR,
     EMP_CODTPL,
     EMP_CODPLZ,
     EMP_CONTRATO_INI, 
     EMP_CONTRATO_FIN,
     CASE WHEN plz_fecha_fin IS NULL THEN
			1
		ELSE	
			0
	 END plz_indefinida, 
     plz_fecha_ini,
     plz_fecha_fin,
     esa_fecha_vigencia emp_fecha_ultimo_incremento,
     isnull(gen.get_pb_field_data_bit(emp_property_bag_data, ''descuentaSeguroSocial''), cast(1 as bit)) dpl_seguro_social,
     isnull(gen.get_pb_field_data_bit(emp_property_bag_data, ''descuentaRenta''), cast(1 as bit)) dpl_renta,
     isnull(gen.get_pb_field_data_bit(emp_property_bag_data, ''AnticipoEspecifico''), cast(0 as bit)) dpl_anticipo_activo,
     isnull(gen.get_pb_field_data_bit(emp_property_bag_data, ''DescuentaOrnato''), cast(1 as bit)) dpl_descuenta_ornato,
     isnull(gen.get_pb_field_data_float(emp_property_bag_data, ''PorcentajeAnticipo''), 0.00) dpl_porcentaje_anticipo
from exp.emp_empleos 
join eor.plz_plazas on plz_codigo = emp_codplz
join exp.esa_est_sal_actual_empleos_v on esa_codemp = emp_codigo and esa_es_salario_base = 1
where plz_codcia = $$CODCIA$$
     and emp_estado = ''A''
     and emp_codtpl = case when $$CODTPL$$ in (select distinct emp_codtpl from exp.emp_empleos where emp_estado = ''A'') then 
                             $$CODTPL$$
                         else 
                             emp_codtpl 
                         end
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', emp_codigo) = 1','emp_codigo','','','TodosExcluyendo',1,0);


commit transaction;