/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'BoletoOrnato';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','BoletoOrnato','BoletoOrnato','select 0.00 bor_monto_inicial, 0.00 bor_monto_final, 0.00 bor_monto_descuento','declare @codcia int
	set @codcia = $$CODCIA$$

	declare @codpai varchar(2)
	select @codpai = cia_codpai from eor.cia_companias where cia_codigo = @codcia

	select inicio bor_monto_inicial, fin bor_monto_final, valor bor_monto_descuento  
	from gen.get_valor_rango_parametro(''BoletoOrnato'', @codpai, null, null, null, null)','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'DescuentosCiclicosPorcentaje';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codppl,fcu_field_codtpl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','DescuentosCiclicosPorcentaje','DescuentosCiclicosPorcentaje','SELECT DCC_CODIGO,
		DCC_CODEMP,
		DCC_FECHA_INICIO_DESCUENTO,
		DCC_FRECUENCIA_CUOTA,
		DCC_CODTPL,
		PPL_CODIGO,
		DCC_PORCENTAJE,
		DCC_CODAGR,
		DCC_CODTDC,
		DCC_CODMON
	FROM SAL.dcc_descuentos_ciclicos JOIN SAL.ppl_periodos_planilla ON
			DCC_CODTPL = ppl_codtpl AND DCC_FECHA_INICIO_DESCUENTO <= PPL_FECHA_FIN
	WHERE DCC_CODIGO = 0','SELECT DCC_CODIGO,
		DCC_CODEMP,
		DCC_FECHA_INICIO_DESCUENTO,
		DCC_FRECUENCIA_CUOTA,
		DCC_CODTPL,
		PPL_CODIGO,
		DCC_PORCENTAJE,
		DCC_CODAGR,
		DCC_CODTDC,
		DCC_CODMON
	FROM SAL.dcc_descuentos_ciclicos JOIN SAL.ppl_periodos_planilla ON
			DCC_CODTPL = ppl_codtpl AND DCC_FECHA_INICIO_DESCUENTO <= PPL_FECHA_FIN
	WHERE DCC_CODTPL = $$CODTPL$$
		AND ppl_codIGO = $$CODPPL$$
		AND DCC_PORCENTAJE > 0
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', dcc_codemp) = 1','DCC_CODEMP','PPL_CODIGO','DCC_CODTPL','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'DescuentosCiclicos';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codcia,fcu_field_codppl,fcu_field_codtpl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','DescuentosCiclicos','DescuentosCiclicos','select *   from sal.cdc_cuotas_descuento_ciclico join sal.dcc_descuentos_ciclicos on 
	cdc_coddcc = dcc_codigo 
where cdc_codigo < 0','select *   from sal.cdc_cuotas_descuento_ciclico join sal.dcc_descuentos_ciclicos on 
	cdc_coddcc = dcc_codigo
where cdc_codppl = $$CODPPL$$  
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', dcc_codemp) = 1','dcc_codemp','cdc_codcia','cdc_codppl','dcc_codtpl','TodosExcluyendo',0,1);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'DescuentosEstaPlanilla';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codppl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','DescuentosEstaPlanilla','DescuentosEstaPlanilla','select * from tmp.dss_descuentos
	where dss_codigo < 0','select * 
from tmp.dss_descuentos
where dss_codppl = $$CODPPL$$
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', dss_codemp) = 1','dss_codemp','dss_codppl','TodosExcluyendo',0,1);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'Amonestaciones';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codcia,fcu_field_codppl,fcu_field_codtpl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','Amonestaciones','Amonestaciones','Select 0 AMO_CODCIA,
        AMO_CODIGO, 
		AMO_CODEMP, 
		AMO_CODTAM, 
		AMO_INICIO_SUSPENSION, 
		AMO_FINAL_SUSPENSION, 
		0 AMO_SUSPENSION_INCLUYE_SEPTIMO, 
		amo_valor_A_DESCONTAR, 
		amo_dias_SUSPENSION, 
		AMO_HORAS_SUSPENSION,
		0 amo_codtpl,   
		amo_codppl_suspension,
		0 DIAS
	from ACC.AMO_AMONESTACIONES
	WHERE amo_codigo < 0','Select 0 AMO_CODCIA,
        AMO_CODIGO, 
		AMO_CODEMP, 
		AMO_CODTAM, 
		AMO_INICIO_SUSPENSION, 
		AMO_FINAL_SUSPENSION, 
		AMO_SUSP_INCLUYE_SEPTIMO AMO_SUSPENSION_INCLUYE_SEPTIMO, 
		amo_valor_A_DESCONTAR, 
		amo_dias_SUSPENSION, 
		AMO_HORAS_SUSPENSION,
		0 amo_codtpl,   
		amo_codppl_suspension,
		CASE WHEN (AMO_INICIO_SUSPENSION < PPL_FECHA_INI AND AMO_FINAL_SUSPENSION > PPL_FECHA_FIN) THEN
				gen.fn_DIFF_TWO_DATES_30(PPL_FECHA_INI, PPL_FECHA_FIN)
			WHEN (AMO_INICIO_SUSPENSION < PPL_FECHA_INI AND AMO_FINAL_SUSPENSION >= PPL_FECHA_INI AND AMO_FINAL_SUSPENSION <= PPL_FECHA_FIN) THEN
				gen.fn_DIFF_TWO_DATES_30(PPL_FECHA_INI, AMO_FINAL_SUSPENSION)
			WHEN (AMO_INICIO_SUSPENSION >= PPL_FECHA_INI AND AMO_INICIO_SUSPENSION <= PPL_FECHA_FIN AND AMO_FINAL_SUSPENSION >= PPL_FECHA_FIN) THEN
				gen.fn_DIFF_TWO_DATES_30(AMO_INICIO_SUSPENSION, PPL_FECHA_FIN)
			WHEN (AMO_INICIO_SUSPENSION >= PPL_FECHA_INI AND AMO_FINAL_SUSPENSION <= PPL_fECHA_FIN) THEN
				gen.fn_DIFF_TWO_DATES_30(AMO_INICIO_SUSPENSION, AMO_FINAL_SUSPENSION)
		END DIAS
	from ACC.AMO_AMONESTACIONES JOIN sal.ppl_periodos_planilla ON
		amo_codppl_suspension = ppl_codigo
	WHERE amo_estado = ''Autorizado'' 
	    and amo_aplica_suspension = 1
		and amo_codppl_suspension = $$CODPPL$$
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', amo_codemp) = 1','amo_codemp','','amo_codppl_suspension','','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'DiasVacaciones';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codcia,fcu_field_codppl,fcu_field_codtpl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','DiasVacaciones','DiasVacaciones','select 0 dva_codcia, 
        0 ppl_codtpl, 
        0 ppl_codpla, 
        0 dva_codemp,
		dva_desde, 
		dva_hasta, 
		0 dias_vacaciones
	from ACC.DVA_DIAS_VACACION
	where dva_codigo < 1
		','select 0 dva_codcia, 
     ppl_codtpl, 
     ppl_codigo ppl_codpla,
     vac_codemp dva_codemp,
     dva_desde, 
     dva_hasta, 
	case when dva_desde <= ppl_fecha_ini and dva_hasta >= ppl_fecha_fin then
				gen.fn_DIFF_TWO_DATES_30(ppl_fecha_ini, ppl_fecha_fin)
			when dva_desde <= ppl_fecha_ini and dva_hasta >= ppl_fecha_ini and dva_hasta <= ppl_fecha_fin then
				gen.fn_DIFF_TWO_DATES_30(ppl_fecha_ini, dva_hasta)
			when dva_desde >= ppl_fecha_ini and dva_desde <= ppl_fecha_fin and dva_hasta >= ppl_fecha_fin then
				gen.fn_DIFF_TWO_DATES_30(dva_desde, ppl_fecha_fin)
			when dva_desde >= ppl_fecha_ini and dva_hasta <= ppl_fecha_fin then
				gen.fn_DIFF_TWO_DATES_30(dva_desde, dva_hasta)
			else
				0
			end dias_vacaciones
from ACC.dva_dias_vacacion JOIN ACC.vac_vacaciones ON
           dva_codvac = vac_codigo
     join SAL.ppl_periodos_planilla on
	     ((dva_desde <= ppl_fecha_ini and dva_hasta >= ppl_fecha_fin) or
				(dva_desde <= ppl_fecha_ini and dva_hasta >= ppl_fecha_ini and dva_hasta <= ppl_fecha_fin) or
				(dva_desde >= ppl_fecha_ini and dva_desde <= ppl_fecha_fin and dva_hasta >= ppl_fecha_fin) or
				(dva_desde >= ppl_fecha_ini and dva_hasta <= ppl_fecha_fin))
where ppl_codigo = $$CODPPL$$
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', vac_codemp) = 1','dva_codemp','','ppl_codpla','ppl_codtpl','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'Vacaciones';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codppl,fcu_field_codtpl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','Vacaciones','Pago por Vacaciones gozadas','select 0    vca_codtpl,
       0    vca_codppl, 
       0    vca_codemp, 
       0    vca_dias_gozados,
       0    vca_dias_calendario, 
       0.00 vca_valor_bono, 
       0.00 vca_valor_vacaciones, 
       0.00 vca_valor_vacaciones_extras ','select vca_codtpl,
       vca_codppl, 
       vca_codemp, 
       vca_dias_gozados,
       vca_dias_calendario, 
       vca_valor_bono, 
       vca_valor_vacaciones, 
       vca_valor_vacaciones_extras 
  from sal.vca_vacaciones_calculadas
   	where vca_codppl = $$CODPPL$$
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', vca_codemp) = 1','vca_codemp','vca_codppl','vca_codtpl','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'DiasIncapacidades';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codcia,fcu_field_codppl,fcu_field_codtpl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','DiasIncapacidades','DiasIncapacidades','select 0 ixe_codcia, 
		ixe_codemp,
		ixe_es_indefinida ixe_indefinida,
		ixe_inicio,
		ixe_final,
		0 ppl_codtpl,
		0 PPL_CODPLA,
		0 DIAS
	from ACC.ixe_incapacidades
	where ixe_codigo = 0','select 0 ixe_codcia,
		ixe_codemp, 
		ixe_es_indefinida ixe_indefinida, 
		ixe_inicio,
		ixe_final,
		ppl_codtpl,
		ppl_codigo PPL_CODPLA,
		CASE WHEN IXE_INICIO < PPL_FECHA_INI AND (IXE_FINAL > PPL_FECHA_FIN OR IXE_FINAL IS NULL) THEN
				gen.fn_DIFF_TWO_DATES_30(PPL_FECHA_INI, PPL_FECHA_FIN)
			WHEN IXE_INICIO <= PPL_FECHA_INI AND IXE_FINAL > PPL_FECHA_INI AND IXE_FINAL <= PPL_FECHA_FIN THEN
				gen.fn_DIFF_TWO_DATES_30(PPL_FECHA_INI, IXE_FINAL)
			WHEN IXE_INICIO >= PPL_FECHA_INI AND IXE_INICIO <= PPL_FECHA_FIN AND IXE_FINAL <= PPL_FECHA_FIN THEN
				gen.fn_DIFF_TWO_DATES_30(IXE_INICIO, IXE_FINAL)
			WHEN IXE_INICIO >= PPL_FECHA_INI AND IXE_INICIO <= PPL_FECHA_FIN AND (IXE_FINAL > PPL_FECHA_FIN OR IXE_FINAL IS NULL) THEN
				gen.fn_DIFF_TWO_DATES_30(IXE_INICIO, PPL_FECHA_FIN)
		END DIAS
	from ACC.ixe_incapacidades join SAL.ppl_periodos_planilla on   
		((IXE_INICIO < PPL_FECHA_INI AND (IXE_FINAL > PPL_FECHA_FIN OR IXE_FINAL IS NULL))
			OR (IXE_INICIO <= PPL_FECHA_INI AND IXE_FINAL > PPL_FECHA_INI AND IXE_FINAL <= PPL_FECHA_FIN)
			OR (IXE_INICIO >= PPL_FECHA_INI AND IXE_INICIO <= PPL_FECHA_FIN AND IXE_FINAL <= PPL_FECHA_FIN) 
			OR (IXE_INICIO >= PPL_FECHA_INI AND IXE_INICIO <= PPL_FECHA_FIN AND (IXE_FINAL > PPL_FECHA_FIN OR IXE_FINAL IS NULL)))
	where PPL_CODIGO = $$CODPPL$$
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', ixe_codemp) = 1','ixe_codemp','','ppl_codpla','ppl_codtpl','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'HorasExtras';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codcia,fcu_field_codppl,fcu_field_codtpl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','HorasExtras','HorasExtras','Select  0 EXT_CODCIA,
    EXT_CODEMP,
    EXT_CODTHE,
    EXT_FECHA EXT_FECHA_INI,
	0 EXT_CODTPL,
	EXT_CODPPL EXT_CODPLA,
	EXT_NUM_HORAS EXT_NUMERO_HORA,
	EXT_VALOR_A_PAGAR EXT_VALOR,
	EXT_FACTOR EXT_VALOR_EXTRA,
	0 THE_CODTIG,
	EXT_CODMON
from sal.ext_horas_extras
where ext_codIGO < 0','Select  0 EXT_CODCIA,
    EXT_CODEMP,
    EXT_CODTHE,
    EXT_FECHA EXT_FECHA_INI,
	ppl_codtpl EXT_CODTPL,
	EXT_CODPPL EXT_CODPLA,
	EXT_NUM_HORAS EXT_NUMERO_HORA,
	EXT_VALOR_A_PAGAR EXT_VALOR,
	EXT_FACTOR EXT_VALOR_EXTRA,
	THE_CODTIG,
	EXT_CODMON
from sal.ext_horas_extras  inner join SAL.the_tipos_hora_extra on       
		the_codigo = ext_codthe  
	JOIN sal.ppl_periodos_planilla ON
		ext_codppl = ppl_codigo
where ext_estado = ''Autorizado''
     and ext_ignorar_en_planilla = 0
     and ext_codppl = $$CODPPL$$
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', ext_codemp) = 1','ext_codemp','','ext_codpla','ext_codtpl','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'RetroactivosBonoLey';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codppl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','RetroactivosBonoLey','RetroactivosBonoLey','SELECT PIR_CODIGO,
	PIR_CODPPL, 
	PIR_CODEMP, 
	PIR_MONTO_RETROACTIVO, 
	PIR_DIAS_RETROACTIVO, 
	PIR_CODRSA
FROM TMP.PIR_PAGOS_INC_RETROACT
WHERE PIR_CODIGO < 0','SELECT PIR_CODIGO,
	PIR_CODPPL, 
	PIR_CODEMP, 
	PIR_MONTO_RETROACTIVO, 
	PIR_DIAS_RETROACTIVO, 
	PIR_CODRSA
FROM TMP.PIR_PAGOS_INC_RETROACT
WHERE PIR_CODPPL = $$CODPPL$$
	AND PIR_CODRSA = 9
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', pir_codemp) = 1','PIR_CODEMP','PIR_CODPPL','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'RetroactivosBonoPactado';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codppl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','RetroactivosBonoPactado','RetroactivosBonoPactado','SELECT PIR_CODIGO,
	PIR_CODPPL, 
	PIR_CODEMP, 
	PIR_MONTO_RETROACTIVO, 
	PIR_DIAS_RETROACTIVO, 
	PIR_CODRSA
FROM TMP.PIR_PAGOS_INC_RETROACT
WHERE PIR_CODIGO < 0','SELECT PIR_CODIGO,
	PIR_CODPPL, 
	PIR_CODEMP, 
	PIR_MONTO_RETROACTIVO, 
	PIR_DIAS_RETROACTIVO, 
	PIR_CODRSA
FROM TMP.PIR_PAGOS_INC_RETROACT
WHERE PIR_CODPPL = $$CODPPL$$
	AND PIR_CODRSA = 10
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', pir_codemp) = 1','PIR_CODEMP','PIR_CODPPL','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'RetroactivosSalario';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codppl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','RetroactivosSalario','RetroactivosSalario','SELECT PIR_CODIGO,
	PIR_CODPPL, 
	PIR_CODEMP, 
	PIR_MONTO_RETROACTIVO, 
	PIR_DIAS_RETROACTIVO, 
	PIR_CODRSA
FROM TMP.PIR_PAGOS_INC_RETROACT
WHERE PIR_CODIGO < 0','SELECT PIR_CODIGO,
	PIR_CODPPL, 
	PIR_CODEMP, 
	PIR_MONTO_RETROACTIVO, 
	PIR_DIAS_RETROACTIVO, 
	PIR_CODRSA
FROM TMP.PIR_PAGOS_INC_RETROACT
WHERE PIR_CODPPL = $$CODPPL$$
	AND PIR_CODRSA = 1
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', pir_codemp) = 1','PIR_CODEMP','PIR_CODPPL','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'ISRCalculado';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codcia,fcu_field_codppl,fcu_field_codtpl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','ISRCalculado','ISRCalculado','SELECT ICI_CODEMP,
	   ICI_RENTA_BRUTA,
	  (ICI_AGUINALDO_DEDUCIBLE + 
	   ICI_BONO14_DEDUCIBLE) ICI_INGRESOS_EXCENTOS,
	   ICI_PERIODOS_PROYECTAR,
	  (ICI_MINIMO_VITAL + 
	   ICI_IGSS_DESCONTADO + 
	   ICI_IGSS_PROYECTADO +
	   ICI_DONACIONES + 
	   ICI_OTROS_DEDUCIBLES) ICI_DEDUCIBLES,
	   ICI_ISR_RETENIDO,
	   ICI_RETENCION_MENSUAL,
       iaf_fecha_ini,
       iaf_fecha_fin
FROM gt.ici_isr_calculado JOIN gt.iaf_anios_fiscales ON
	ici_codiaf = iaf_codigo
WHERE ici_codigo < 0','DECLARE @CODCIA INT,
	    @CODTPL INT,
	    @CODPPL INT,
	    @PPL_FECHA_INI DATETIME,
	    @PPL_FECHA_FIN DATETIME
	
SET @CODCIA =  $$CODCIA$$
SET @CODTPL = $$CODTPL$$
SET @CODPPL = $$CODPPL$$

SELECT @PPL_FECHA_INI = PPL_FECHA_INI,
	   @PPL_FECHA_FIN = PPL_FECHA_FIN
from sal.ppl_periodos_planilla
where ppl_codigo = @codppl;

SELECT 
	ICI_CODEMP,
	ICI_RENTA_BRUTA,
	(ICI_AGUINALDO_DEDUCIBLE + 
		ICI_BONO14_DEDUCIBLE) ICI_INGRESOS_EXCENTOS,
	ICI_PERIODOS_PROYECTAR,
	(ICI_MINIMO_VITAL + 
		ICI_IGSS_DESCONTADO + 
		ICI_IGSS_PROYECTADO +
		ICI_DONACIONES + 
		ICI_OTROS_DEDUCIBLES) ICI_DEDUCIBLES,
	ICI_ISR_RETENIDO,
    ICI_RETENCION_MENSUAL,
	iaf_fecha_ini,
    iaf_fecha_fin
FROM gt.ici_isr_calculado 
  JOIN gt.iaf_anios_fiscales ON	ici_codiaf = iaf_codigo
WHERE ((@PPL_FECHA_INI BETWEEN IAF_FECHA_INI AND IAF_FECHA_FIN) OR
		(@PPL_FECHA_FIN BETWEEN IAF_FECHA_INI AND IAF_FECHA_FIN)) 
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', ici_codemp) = 1','ici_codemp','','','','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'ComplementosSalario';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codppl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','ComplementosSalario','Empleados de Nuevo Ingreso que iniciaron luego de pagada la planilla','SELECT *
FROM tmp.ENI_EMPLEADO_NUEVO_INGRESO
WHERE ENI_CODPPL = 0
','SELECT *
FROM tmp.ENI_EMPLEADO_NUEVO_INGRESO
WHERE ENI_CODPPL = $$CODPPL$$
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', eni_codemp) = 1
','ENI_CODEMP','ENI_CODPPL','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'DescuentosEventuales';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codcia,fcu_field_codppl,fcu_field_codtpl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','DescuentosEventuales','DescuentosEventuales','select * 
  from sal.ods_otros_descuentos
 where ods_codigo < 0','select * 
from sal.ods_otros_descuentos
where ods_estado = ''Autorizado'' 
   and ods_ignorar_en_planilla = 0
   and ods_codppl = $$CODPPL$$
   and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', ods_codemp) = 1','ods_codemp','','ods_codppl','','TodosExcluyendo',0,1);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'IngresosEventuales';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codcia,fcu_field_codppl,fcu_field_codtpl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','IngresosEventuales','IngresosEventuales','select *
  from sal.oin_otros_ingresos
 where oin_codigo < 0','select *
  from sal.oin_otros_ingresos
 where oin_estado = ''Autorizado''
   and oin_ignorar_en_planilla = 0
   and oin_codppl = $$CODPPL$$
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', oin_codemp) = 1
','oin_codemp','','oin_codppl','','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'CalculosAguinaldo';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codppl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','CalculosAguinaldo','Obtiene los datos calculados de Aguinaldo','SELECT CAG_CODPPL,
	CAG_CODEMP,
	CAG_MONTO_PAGAR,
	CAG_PROMEDIO_ORDINARIO,
	CAG_PROMEDIO_BONILEY,
	CAG_DIAS_TRABAJADOS
FROM gt.CAG_CALCULO_AGUINALDO
WHERE CAG_CODPPL = 0','SELECT CAG_CODPPL,
	CAG_CODEMP,
	CAG_MONTO_PAGAR,
	CAG_PROMEDIO_ORDINARIO,
	CAG_PROMEDIO_BONILEY,
	CAG_DIAS_TRABAJADOS
FROM gt.CAG_CALCULO_AGUINALDO
WHERE CAG_CODPPL = $$CODPPL$$
','CAG_CODEMP','CAG_CODPPL','TodosExcluyendo',1,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'CalculosBono14';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codppl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','CalculosBono14','Trae los datos calculados en la Inicializacion, sobre bono 14','SELECT B14_CODPPL,
	B14_CODEMP,
	B14_MONTO_PAGAR,
	B14_PROMEDIO_ORDINARIO,
	B14_PROMEDIO_BONILEY,
	B14_DIAS_TRABAJADOS
FROM gt.B14_CALCULO_BONO14
WHERE B14_CODPPL = 0
','SELECT B14_CODPPL,
	B14_CODEMP,
	B14_MONTO_PAGAR,
	B14_PROMEDIO_ORDINARIO,
	B14_PROMEDIO_BONILEY,
	B14_DIAS_TRABAJADOS
FROM gt.B14_CALCULO_BONO14
WHERE B14_CODPPL = $$CODPPL$$
','B14_CODEMP','B14_CODPPL','TodosExcluyendo',1,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'Sustituciones';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codppl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','Sustituciones','Para calculo del pago de sustituciones temporales','Select
0 ste_codppl,
0 ste_codemp,
0.00 ste_valor,
0 ste_dias','Select ste_codppl, 
       ste_codemp, 
       ROUND((ste_salario_titular - ste_salario_sustituto) / 30 * ste_dias,2) ste_valor, 
       ste_dias
from (
select
     ppl_codigo ste_codppl, 
     ste_codemp_sustito ste_codemp, 
     t.ese_valor ste_salario_titular, 
     s.ese_valor ste_salario_sustituto, 
     ste_codemp_sustito, 
DATEDIFF(dd,
    case 
      when ste_fecha_inicio < ppl_fecha_ini
           then ppl_fecha_ini
           else ste_fecha_inicio
           end,
    case 
      when ste_fecha_fin > ppl_fecha_fin
           then ppl_fecha_fin
           else ste_fecha_fin
           end) + 1 ste_dias
 from acc.ste_sustituciones_temp
join exp.emp_empleos on emp_codigo = ste_codemp_titular
join eor.plz_plazas on plz_codigo = emp_codplz
join sal.ppl_periodos_planilla on ppl_codtpl = emp_codtpl
join exp.rsa_rubros_salariales on rsa_codcia = plz_codcia AND rsa_es_salario_base = 1
join exp.ese_estructura_sal_empleos t on t.ese_codemp = ste_codemp_titular and t.ese_codrsa = rsa_codigo
join exp.ese_estructura_sal_empleos s on s.ese_codemp = ste_codemp_sustito and s.ese_codrsa = rsa_codigo
where ppl_codigo = $$CODPPL$$
and ste_fecha_inicio between ppl_fecha_ini and ppl_fecha_fin
and t.ese_valor > s.ese_valor) v1','ste_codemp','ste_codppl','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'TiemposNoTrabajados';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codcia,fcu_field_codppl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','TiemposNoTrabajados','TiemposNoTrabajados','SELECT tnn_codigo,
	tnn_codemp,
	tnn_fecha_del,
	tnn_fecha_al,
	tnn_num_dias + isnull(tnn_num_horas / 8, 0) dias,
	tnn_codppl
 FROM sal.tnn_tiempos_no_trabajados join sal.tnt_tipos_tiempo_no_trabajado on 
	tnt_codigo = tnn_codtnt
 WHERE tnn_codigo < 0','SELECT tnn_codigo,
	tnn_codemp,
	tnn_fecha_del,
	tnn_fecha_al,
	tnn_num_dias + isnull(tnn_num_horas / 8, 0) dias,
	tnn_codppl
 FROM sal.tnn_tiempos_no_trabajados join sal.tnt_tipos_tiempo_no_trabajado on 
	tnt_codigo = tnn_codtnt
 WHERE tnn_estado = ''Autorizado'' 
   and tnn_ignorar_en_planilla = 0
   and tnn_codppl = $$CODPPL$$
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', tnn_codemp) = 1','tnn_codemp','','tnn_CODPPL','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'ParametrosAplicacion';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codcia,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','ParametrosAplicacion','ParametrosAplicacion','select 0 pge_mes_descontar_boleto,
    0 pge_quincena_descontar_boleto,
	0 pge_quincena_descontar_isr,
	0.00 pge_porcentaje_anticipo,
	0.00 pge_porcentaje_solidarismo,
	0.00 pge_porcentaje_sindical','declare @codcia int
set @codcia = $$CODCIA$$

declare @codpai varchar(2),
	@codgrc int
	
select @codpai = cia_codpai,
	@codgrc = cia_codgrc
from eor.cia_companias 
where cia_codigo = @codcia

select isnull(gen.get_valor_parametro_int(''BoletoOrnatoMesDescuento'', @codpai, null, null, null), 0) pge_mes_descontar_boleto,
    isnull(gen.get_valor_parametro_int(''BoletoOrnatoFrecuenciaDesc'', @codpai, null, null, null), 0) pge_quincena_descontar_boleto,
	isnull(gen.get_valor_parametro_int(''ISRQuincenaDescuento'', @codpai, null, null, null), 0)pge_quincena_descontar_isr,
	isnull(gen.get_valor_parametro_float(''PorcentajeAnticipoEmpresa'', null, null, @codcia, null), 0) pge_porcentaje_anticipo,
	isnull(gen.get_valor_parametro_float(''CocaPorcentajesolidarismo'', null, null, @codcia, null), 0) pge_porcentaje_solidarismo,
	isnull(gen.get_valor_parametro_float(''CocaPorcentajesindical'', null, null, @codcia, null), 0) pge_porcentaje_sindical','','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'IngresosCiclicos';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codppl,fcu_field_codtpl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','IngresosCiclicos','Detalle de Ingresos Ciclicos para pagar a los empleados','select *   from sal.cic_cuotas_ingreso_ciclico join sal.igc_ingresos_ciclicos on 
	cic_codigc = igc_codigo
where cic_codigo = 0','select *   from sal.cic_cuotas_ingreso_ciclico join sal.igc_ingresos_ciclicos on 
	cic_codigc = igc_codigo
where cic_codppl = $$CODPPL$$  
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', igc_codemp) = 1','igc_codemp','cic_codppl','igc_codtpl','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'IngresosEstaPlanilla';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codcia,fcu_field_codppl,fcu_field_codtpl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','IngresosEstaPlanilla','IngresosEstaPlanilla','select * 
  from tmp.inn_ingresos
 where inn_codigo < 0','select * 
  from tmp.inn_ingresos
 where inn_codppl = $$CODPPL$$
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', inn_codemp) = 1','inn_codemp','','inn_codppl','','TodosExcluyendo',0,1);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'IngresosPlanillaAnterior';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','IngresosPlanillaAnterior','IngresosPlanillaAnterior','select * 
from sal.inn_ingresos
where inn_codigo < 0','select * 
from sal.inn_ingresos
where inn_codppl IN (select ppl_codigo
					from sal.ppl_periodos_planilla
					where ppl_codtpl = $$CODTPL$$
						and ppl_mes = (select ppl_mes
											from sal.ppl_periodos_planilla
											where ppl_codigo = $$CODPPL$$)
						and ppl_anio = (select ppl_anio
												from sal.ppl_periodos_planilla
												where ppl_codigo = $$CODPPL$$)
						and ppl_frecuencia = 1)
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', inn_codemp) = 1','inn_codemp','TodosExcluyendo',0,1);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'TablaISR';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','TablaISR','Tabla de ISR Guatemala','select inicio isr_desde, fin isr_hasta, porcentaje isr_pct, excedente isr_excedente, valor isr_valor
from gen.get_valor_rango_parametro(''TablaRentaNueva'', ''gt'', null, null, null, null)
where inicio <0','select inicio isr_desde, fin isr_hasta, porcentaje isr_pct, excedente isr_excedente, valor isr_valor
from gen.get_valor_rango_parametro(''TablaRentaNueva'', ''gt'', null, null, null, null)','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'ParametrosIGSS';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codcia,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','ParametrosIGSS','ParametrosIGSS','SELECT 0 EMP_CODCIA,
	0 EMP_CODIGO,
	0.00 ubi_porcentaje_cuota_isss,
	0.00 ubi_pag_porcent_igss_patrono,
	0.00 ubi_intecap,
	0.00 ubi_irtra','SELECT plz_codcia emp_codcia,
	emp_codigo,
    ubi_porcentaje_cuota_isss,
	ubi_pag_porcent_igss_patrono,
	ubi_intecap,
	ubi_irtra
FROM eor.plz_plazas 
JOIN (SELECT cdt_codigo, 
			 isnull(gen.get_valor_parametro_float(''CuotaEmpleadoSeguroSocial'',''gt'', null, null, null), 0.00) ubi_porcentaje_cuota_isss,
	isnull(gen.get_valor_parametro_float(''CuotaPatronoSeguroSocial'', ''gt'', null, null,null), 0.00) ubi_pag_porcent_igss_patrono,
	isnull(gen.get_valor_parametro_float(''CuotaPatronalIRTRA'',''gt'', null, null, null), 0.00) ubi_intecap,
	isnull(gen.get_valor_parametro_float(''CuotaPatronalIRTRA'', ''gt'', null, null, null), 0.00) ubi_irtra
	  FROM eor.cdt_centros_de_trabajo
	  ) cdt ON cdt_codigo = plz_codcdt
JOIN EXP.emp_empleos ON
     plz_codigo = emp_codplz
WHERE plz_codcia = $$CODCIA$$
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', emp_codigo) = 1','emp_codigo','','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'Periodos';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codcia,fcu_field_codppl,fcu_field_codtpl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','Periodos','Periodos','select sal.ppl_periodos_planilla.*, 
       sal.tpl_tipo_planilla.*, 
       cia_periodo
from sal.ppl_periodos_planilla join sal.tpl_tipo_planilla on 
          tpl_codigo = ppl_codtpl
      join eor.cia_companias on 
          cia_codigo = tpl_codcia
where 1 = 0','select sal.ppl_periodos_planilla.*, 
       sal.tpl_tipo_planilla.*, 
       cia_periodo,
       case when month(ppl_fecha_fin) = isnull(gen.get_valor_parametro_int(''AguinaldoMesParaCalculo'', cia_codpai, null, null, null), 12) then 1 else 0 end ppl_calcula_aguinaldo,
       cast(cast(year(ppl_fecha_fin) as varchar) + ''0101'' as datetime) ppl_fecha_ini_aguinaldo,
       cast(cast(year(ppl_fecha_fin) as varchar) + ''1231'' as datetime) ppl_fecha_fin_aguinaldo
from sal.ppl_periodos_planilla join sal.tpl_tipo_planilla on 
          tpl_codigo = ppl_codtpl
     join eor.cia_companias on 
          cia_codigo = tpl_codcia
where ppl_codigo = $$CODPPL$$','','ppl_codigo','ppl_codtpl','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'PeriodoAnterior';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codppl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','PeriodoAnterior','PeriodoAnterior','select PPL_CODTPL, 
	PPL_CODIGO, 
	PPL_FECHA_INI,              
	PPL_FECHA_FIN, 
	PPL_FECHA_PAGO, 
	PPL_ESTADO, 
	PPL_FRECUENCIA,              
	PPL_MES, 
	ppl_anio
from sal.ppl_periodos_planilla
where ppl_codigo < 0','select PPL_CODTPL, 
	PPL_CODIGO, 
	PPL_FECHA_INI,              
	PPL_FECHA_FIN, 
	PPL_FECHA_PAGO, 
	PPL_ESTADO, 
	PPL_FRECUENCIA,              
	PPL_MES, 
	ppl_anio
from sal.ppl_periodos_planilla
where ppl_codtpl = $$CODTPL$$
	and ppl_mes = (select ppl_mes
						from sal.ppl_periodos_planilla
						where ppl_codigo = $$CODPPL$$)
	and ppl_anio = (select ppl_anio
							from sal.ppl_periodos_planilla
							where ppl_codigo = $$CODPPL$$)
	and ppl_frecuencia = 1','ppl_codigo','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'PrestacionesEmpleado';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codcia,fcu_field_codppl,fcu_field_codtpl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','PrestacionesEmpleado','PrestacionesEmpleado','select 0 ppe_codemp,
       0 ppe_codpres,
       getdate() ppe_fecha_ini,
       getdate() ppe_fecha_fin,
       0.00 ppe_valor,
       0 ppe_frecuencia,
       0 PRE_CODINGRESO,
       '''' ppp_codmon
','declare @codcia int, 
     @codtpl int, 
     @codppl INT, 
     @fre int, 
     @fin DATETIME

set @codcia = $$CODCIA$$
set @codtpl = $$CODTPL$$
set @codppl = $$CODPPL$$

-- Obtiene la fecha de finalizacion de la planilla y la frecuencia
select @fre = cast(ppl_frecuencia as int),
       @fin = ppl_fecha_fin
from sal.ppl_periodos_planilla
where ppl_codigo = @codppl;
   
select emp_codigo ppe_codemp,
     ppp_fecha_ini ppe_fecha_ini, 
     ppp_fecha_fin ppe_fecha_fin,
     case when isnull(pre_tipo, ''V'') = ''H'' then 
          round(ppp_valor * esa_valor_hora, 2)
     else 
          ppp_valor 
     end ppe_valor,
     pre_codfre ppe_frecuencia,
     pre_codtig PRE_CODINGRESO,
     ppp_codmon
from eor.ppp_prestaciones_puesto join eor.pre_prestaciones on 
          ppp_codpre = pre_codigo
     join eor.plz_plazas on 
          ppp_codpue = plz_codpue
     join exp.emp_empleos on 
          plz_codigo = emp_codplz
     join exp.esa_est_sal_actual_empleos_v on 
          esa_codemp = emp_codigo and esa_es_salario_base = 1
     join sal.ppl_periodos_planilla on 
          ppl_codigo = @codppl
where plz_codcia = @codcia
   and emp_codtpl = @codtpl
   and emp_estado = ''A''
   and ppp_fecha_fin >= @fin and ppp_fecha_ini <= @fin
   and pre_codcia = @codcia
   and (pre_codfre = @fre or pre_codfre = 6)
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', emp_codigo) = 1
','ppe_codemp','','','','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'PrestacionesPuesto';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codcia,fcu_field_codppl,fcu_field_codtpl,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','PrestacionesPuesto','PrestacionesPuesto','select GETDATE() PPP_FECHA_INI, 
		GETDATE() PPP_FECHA_FIN, 
		0.00 PPP_VALOR, 
		0 PRE_CODINGRESO, 
		0 PRE_FRECUENCIA,
		'''' ppp_codmon
	','declare @codcia int, 
     @codtpl int, 
     @codppl INT, 
     @fre int, 
     @fin DATETIME

set @codcia = $$CODCIA$$
set @codtpl = $$CODTPL$$
set @codppl = $$CODPPL$$

-- Obtiene la fecha de finalizacion de la planilla y la frecuencia
select @fre = cast(ppl_frecuencia as int),
       @fin = ppl_fecha_fin
from sal.ppl_periodos_planilla
where ppl_codigo = @codppl;

select ppp_fecha_ini ppP_fecha_ini, 
     ppp_fecha_fin ppP_fecha_fin,
     case when isnull(pre_tipo, ''V'') = ''H'' then 
          round(ppp_valor * esa_valor_hora, 2)
     else 
          ppp_valor 
     end ppP_valor,
     pre_codfre PRE_FRECUENCIA,
     pre_codtig PRE_CODINGRESO,
     ppp_codmon
from eor.ppp_prestaciones_puesto join eor.pre_prestaciones on 
          ppp_codpre = pre_codigo
     join eor.plz_plazas on 
          ppp_codpue = plz_codpue
     join exp.emp_empleos on 
          plz_codigo = emp_codplz
     join exp.esa_est_sal_actual_empleos_v on 
          esa_codemp = emp_codigo and esa_es_salario_base = 1
     join sal.ppl_periodos_planilla on 
          ppl_codigo = @codppl
where plz_codcia = @codcia
   and emp_codtpl = @codtpl
   and emp_estado = ''A''
   and ppp_fecha_fin >= @fin and ppp_fecha_ini <= @fin
   and pre_codcia = @codcia
   and (pre_codfre = @fre or pre_codfre = 6)
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', emp_codigo) = 1','','','','','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'RubrosBonoLey';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_field_codcia,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','RubrosBonoLey','Recoge los datos de la Bonificacion de Ley del Empleado','select 0 esa_codemp, 
       0 esa_es_salario_base,
       0.00 esa_valor,
       0 esa_codmon,
       0.00 esa_valor_hora,
       0 esa_num_horas_x_mes,
       '''' esa_exp_valor,
       0.00 esa_valor_anterior,
       getdate() esa_fecha_vigencia,
       0 esa_codtig
','declare @codppl int, 
	@sessionId UNIQUEIDENTIFIER,
	@codrsa INT,
	@ppl_fecha_fin DATETIME,
	@codcia INT
	
set @codppl = $$CODPPL$$
set @sessionId = ''$$SESSIONID$$''
set @codcia = ''$$CODCIA$$''

SET @codrsa = isnull(gen.get_valor_parametro_int (''RSA_Decreto'',null,null,@codcia,null),0)

select @ppl_fecha_fin = ppl_fecha_fin 
from sal.ppl_periodos_planilla 
where ppl_codigo = @codppl

select ese_codemp esa_codemp, 
       rsa_es_salario_base esa_es_salario_base,
       ese_valor esa_valor,
       ese_codmon esa_codmon,
       ese_valor_hora esa_valor_hora,
       ese_num_horas_x_mes esa_num_horas_x_mes,
       ese_exp_valor esa_exp_valor,
       ese_valor_anterior esa_valor_anterior,
       ese_fecha_inicio esa_fecha_vigencia,
       ese_codtig esa_codtig
from exp.ese_estructura_sal_empleos join exp.rsa_rubros_salariales on 
		rsa_codigo = ese_codrsa
	join (SELECT ese_codemp codemp, max(ese_codigo) max_codigo
				FROM exp.ese_estructura_sal_empleos
				where ese_estado = ''V''
					AND ese_codrsa = @codrsa
					and ese_fecha_inicio <= @ppl_fecha_fin
					and isnull(ese_fecha_fin, @ppl_fecha_fin + 1) >= @ppl_fecha_fin
				group by ese_codemp) m on ese_codigo = max_codigo
 where ese_codrsa = @codrsa
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', ese_codemp) = 1

','esa_codemp','','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'RubrosBonoPactado';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','RubrosBonoPactado','Recoge los datos del Salario Ordinario del Empleado','select 0 esa_codemp, 
       0 esa_es_salario_base,
       0.00 esa_valor,
       0 esa_codmon,
       0.00 esa_valor_hora,
       0 esa_num_horas_x_mes,
       '''' esa_exp_valor,
       0.00 esa_valor_anterior,
       getdate() esa_fecha_vigencia,
       0 esa_codtig
','declare @codppl int, 
	@sessionId UNIQUEIDENTIFIER,
	@codrsa INT,
	@ppl_fecha_fin DATETIME,
	@codcia INT
	
set @codppl = $$CODPPL$$
set @sessionId = ''$$SESSIONID$$''
set @codcia = ''$$CODCIA$$''

SET @codrsa = isnull(gen.get_valor_parametro_int (''RSA_Pactado'',null,null,@codcia,null),0)

select @ppl_fecha_fin = ppl_fecha_fin 
from sal.ppl_periodos_planilla 
where ppl_codigo = @codppl

select ese_codemp esa_codemp, 
       rsa_es_salario_base esa_es_salario_base,
       ese_valor esa_valor,
       ese_codmon esa_codmon,
       ese_valor_hora esa_valor_hora,
       ese_num_horas_x_mes esa_num_horas_x_mes,
       ese_exp_valor esa_exp_valor,
       ese_valor_anterior esa_valor_anterior,
       ese_fecha_inicio esa_fecha_vigencia,
       ese_codtig esa_codtig
from exp.ese_estructura_sal_empleos join exp.rsa_rubros_salariales on 
		rsa_codigo = ese_codrsa
	join (SELECT ese_codemp codemp, max(ese_codigo) max_codigo
				FROM exp.ese_estructura_sal_empleos
				where ese_estado = ''V''
					AND ese_codrsa = @codrsa
					and ese_fecha_inicio <= @ppl_fecha_fin
					and isnull(ese_fecha_fin, @ppl_fecha_fin + 1) >= @ppl_fecha_fin
				group by ese_codemp) m on ese_codigo = max_codigo
 where ese_codrsa = @codrsa
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', ese_codemp) = 1
','esa_codemp','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'RubrosSalario';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','RubrosSalario','Recoge los datos del Salario Ordinario del Empleado','select 0 esa_codemp, 
       0 esa_es_salario_base,
       0.00 esa_valor,
       0 esa_codmon,
       0.00 esa_valor_hora,
       0 esa_num_horas_x_mes,
       '''' esa_exp_valor,
       0.00 esa_valor_anterior,
       getdate() esa_fecha_vigencia,
       0 esa_codtig
','declare @codppl int, 
	@sessionId UNIQUEIDENTIFIER,
	@codrsa INT,
	@ppl_fecha_fin DATETIME,
	@codcia INT
	
set @codppl = $$CODPPL$$
set @sessionId = ''$$SESSIONID$$''
set @codcia = ''$$CODCIA$$''

SET @codrsa = isnull(gen.get_valor_parametro_int (''RSA_Salario'',null,null,@codcia,null),0)

select @ppl_fecha_fin = ppl_fecha_fin 
from sal.ppl_periodos_planilla 
where ppl_codigo = @codppl

select ese_codemp esa_codemp, 
       rsa_es_salario_base esa_es_salario_base,
       ese_valor esa_valor,
       ese_codmon esa_codmon,
       ese_valor_hora esa_valor_hora,
       ese_num_horas_x_mes esa_num_horas_x_mes,
       ese_exp_valor esa_exp_valor,
       ese_valor_anterior esa_valor_anterior,
       ese_fecha_inicio esa_fecha_vigencia,
       ese_codtig esa_codtig
from exp.ese_estructura_sal_empleos join exp.rsa_rubros_salariales on 
		rsa_codigo = ese_codrsa
	join (SELECT ese_codemp codemp, max(ese_codigo) max_codigo
				FROM exp.ese_estructura_sal_empleos
				where ese_estado = ''V''
					AND ese_codrsa = @codrsa
					and ese_fecha_inicio <= @ppl_fecha_fin
					and isnull(ese_fecha_fin, @ppl_fecha_fin + 1) >= @ppl_fecha_fin
				group by ese_codemp) m on ese_codigo = max_codigo
 where ese_codrsa = @codrsa
	and sal.empleado_en_gen_planilla(''$$SESSIONID$$'', ese_codemp) = 1
','esa_codemp','TodosExcluyendo',0,0);


commit transaction;

/* Script generated by Evolution - FormulaEditor. 09/09/2013 4:20 PM */

begin transaction

delete from sal.fcu_formulacion_cursores where fcu_codpai = 'gt' and fcu_nombre = 'SegurosMedicos';


insert into sal.fcu_formulacion_cursores (fcu_codpai,fcu_proceso,fcu_nombre,fcu_descripcion,fcu_select_edit,fcu_select_run,fcu_field_codemp,fcu_modo_asociacion_tpl,fcu_loop_calculo,fcu_updatable) values ('gt','Planilla','SegurosMedicos','SegurosMedicos','select 0 sem_codemp,
		0 sem_codsme,
		0 sme_codtsm,
		0.00 sem_cuota_emp,
		0.00 sem_cuota_pat','select sem_codemp,
	sem_codsme,
	SME_CODTSG sme_codtsm,
	sme_cuota_Seguro sem_cuota_emp,
	sme_cuota_familiar sem_cuota_pat
from EXP.sem_seguros_medicos_empleo join EXP.sme_seguros_medicos on
	sem_codsme = sme_codigo
where sal.empleado_en_gen_planilla(''$$SESSIONID$$'', sem_codemp) = 1','sem_codemp','TodosExcluyendo',0,0);


commit transaction;

