BEGIN TRANSACTION

SET DATEFORMAT YMD

DECLARE @codpai VARCHAR(2),
	@codcia INT

SET @codpai = 'cr'

SELECT @codcia = cia_codigo
FROM eor.cia_companias
WHERE cia_codpai = @codpai

INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Salario Ordinario', '1', 1, 10, '600-610-001-002', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, NULL, NULL, '2015-03-13 14:42:26', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Horas Normales', '2', 1, 20, '600-610-001-001', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, NULL, NULL, '2015-03-13 14:42:54', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Horas Extras', '3', 1, 30, '600-610-001-001', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, NULL, NULL, '2015-03-13 14:43:09', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Horas Dobles', '4', 1, 40, '600-610-001-001', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, NULL, NULL, '2015-03-13 14:43:23', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Horas Mixtas Normal', '5', 1, 50, '600-610-001-001', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, NULL, NULL, '2015-03-13 14:43:37', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Horas Mixtas', '6', 1, 60, '600-610-001-001', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, NULL, NULL, '2015-03-13 14:43:53', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Horas Nocturnas', '7', 1, 70, '600-610-001-001', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, NULL, NULL, '2015-03-13 14:44:05', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Día Feriado', '8', 1, 80, '600-610-001-001', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, '2014-11-28 11:53:22', 'admin', '2015-03-13 14:44:58', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Subsidio Incapacidad CCSS', '9', 1, 90, '600-610-001-001', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, '2014-11-28 11:54:24', 'admin', '2015-03-13 14:45:25', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Vacaciones', '10', 1, 100, '200-230-002-001-004', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, '2014-11-28 11:55:04', 'admin', '2015-03-13 14:47:38', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Licencia por Maternidad', '11', 1, 110, '600-610-001-001', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, '2014-11-28 11:55:38', 'admin', '2015-03-13 14:51:24', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Retroactivo Prod', '12', 1, 120, '600-610-001-001', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, '2014-11-28 11:56:23', 'admin', '2015-03-13 14:52:10', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Cita Medica', '13', 1, 130, '600-610-001-001', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, '2014-11-28 11:57:21', 'admin', '2015-03-13 14:52:43', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Aguinaldo', '14', 1, 140, '600-610-001-003', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, '2014-11-28 11:57:54', 'admin', '2015-04-10 08:47:42', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Bonificaciones', '15', 1, 150, '600-610-001-001', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, '2014-11-28 11:58:48', 'admin', '2015-03-13 14:53:36', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Cesantía', '16', 1, 160, '600-620-001-003', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, '2015-02-25 21:27:45', 'admin', '2015-04-10 12:47:57', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Preaviso', '17', 1, 170, '600-610-001-005', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, '2015-02-25 21:28:07', 'admin', '2015-04-10 12:48:04', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Retroactivo Adm', '18', 1, 180, '600-610-001-002', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, '2015-03-13 14:56:19', 'admin', '2015-04-10 12:48:11', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Licencia Equipo Especial', '19', 1, 190, '600-610-001-001', NULL, NULL, NULL, '', 'Autorizado', NULL, 0, '2015-04-10 12:50:12', 'admin', '2015-04-10 12:50:14', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Ahorro Escolar', '20', 1, 160, NULL, NULL, NULL, NULL, '', 'Autorizado', NULL, 0, '2015-03-26 09:27:43', 'admin', '2015-03-26 09:28:02', 'admin')
INSERT sal.tig_tipos_ingreso (tig_codcia, tig_descripcion, tig_abreviatura, tig_activo, tig_orden, tig_cuenta, tig_cuenta_aux, tig_cuenta_patronal, tig_cuenta_patronal_aux, tig_property_bag_data, tig_estado_workflow, tig_codigo_workflow, tig_ingresado_portal, tig_fecha_grabacion, tig_usuario_grabacion, tig_fecha_modificacion, tig_usuario_modificacion) VALUES (@codcia, 'Ahorro Patronal', '21', 1, 170, NULL, NULL, NULL, NULL, '', 'Autorizado', NULL, 0, '2015-03-26 09:33:55', 'admin', '2015-03-26 09:34:05', 'admin')

COMMIT TRANSACTION


